<?php

namespace Database\Seeders;

use App\Models\Party;
use App\Models\Club;
use Illuminate\Database\Seeder;

class AdditionalPartySeeder extends Seeder
{
    public function run(): void
    {
        $today = now();

        // 클럽 ID 매핑 (slug 기반으로 안전하게)
        $clubIds = Club::pluck('id', 'slug')->toArray();

        $parties = [
            // ── 오늘 파티 ──
            [
                'club_id' => $clubIds['venue-hongdae'] ?? null,
                'name' => 'VENUE GRAND OPENING',
                'slug' => 'venue-grand-opening-' . $today->format('Ymd'),
                'event_date' => $today->toDateString(),
                'start_time' => '22:00',
                'end_time' => '06:00',
                'lineup' => 'DJ SODA · RAIDEN · VENUE RESIDENTS',
                'ticket_price_min' => 15000,
                'ticket_price_max' => 25000,
                'genre' => 'EDM',
                'tags' => ['오늘', 'EDM', '홍대', '그랜드오프닝'],
                'dress_code' => '캐주얼',
                'entry_condition' => '19세 이상',
                'description' => 'VENUE 홍대의 그랜드 오프닝 파티! DJ SODA와 함께하는 특별한 밤.',
                'thumbnail' => 'https://images.unsplash.com/photo-1571266028243-e4733b0f0bb0?w=600&q=80',
                'status' => 'upcoming',
            ],
            [
                'club_id' => $clubIds['nb-club'] ?? null,
                'name' => 'NB HIPHOP CYPHER',
                'slug' => 'nb-hiphop-cypher-' . $today->format('Ymd'),
                'event_date' => $today->toDateString(),
                'start_time' => '21:00',
                'end_time' => '05:00',
                'lineup' => 'DJ PUMP · MC META · NAFLA',
                'ticket_price_min' => 10000,
                'ticket_price_max' => 15000,
                'genre' => '힙합',
                'tags' => ['오늘', '힙합', '홍대', '사이퍼'],
                'dress_code' => '자유',
                'entry_condition' => '19세 이상',
                'description' => 'NB클럽의 힙합 사이퍼 나이트. MC META와 NAFLA가 함께합니다.',
                'thumbnail' => 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=600&q=80',
                'status' => 'upcoming',
            ],
            [
                'club_id' => $clubIds['contra'] ?? null,
                'name' => 'DISCO INFERNO',
                'slug' => 'disco-inferno-' . $today->format('Ymd'),
                'event_date' => $today->toDateString(),
                'start_time' => '22:00',
                'end_time' => '06:00',
                'lineup' => 'DJ MOCHI · FUNKMASTER KIM · GROOVE PATROL',
                'ticket_price_min' => 10000,
                'ticket_price_max' => 15000,
                'genre' => '하우스',
                'tags' => ['오늘', '디스코', '이태원', '펑키'],
                'dress_code' => '자유',
                'entry_condition' => '19세 이상',
                'description' => '이태원 CONTRA의 디스코/펑크 나이트. 70-80년대 감성의 현대적 해석.',
                'thumbnail' => 'https://images.unsplash.com/photo-1566417713940-fe7c737a9ef2?w=600&q=80',
                'status' => 'upcoming',
            ],
            [
                'club_id' => $clubIds['golden-goose'] ?? null,
                'name' => 'GOLDEN FRIDAY',
                'slug' => 'golden-friday-' . $today->format('Ymd'),
                'event_date' => $today->toDateString(),
                'start_time' => '22:00',
                'end_time' => '06:00',
                'lineup' => 'DJ WRECKX · JAY PARK (GUEST) · GOLDEN RESIDENTS',
                'ticket_price_min' => 30000,
                'ticket_price_max' => 50000,
                'genre' => '힙합',
                'tags' => ['오늘', '힙합', '압구정', '셀럽'],
                'dress_code' => '세미 포멀',
                'entry_condition' => '20세 이상 / 드레스코드 적용',
                'description' => '압구정 GOLDEN GOOSE의 금요 파티. 특별 게스트와 함께하는 럭셔리한 밤.',
                'thumbnail' => 'https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?w=600&q=80',
                'status' => 'upcoming',
            ],
            [
                'club_id' => $clubIds['kream-club'] ?? null,
                'name' => 'KREAM PARTY',
                'slug' => 'kream-party-' . $today->format('Ymd'),
                'event_date' => $today->toDateString(),
                'start_time' => '21:00',
                'end_time' => '05:00',
                'lineup' => 'DJ HAZE · KREAM CREW',
                'ticket_price_min' => 8000,
                'ticket_price_max' => 12000,
                'genre' => '힙합',
                'tags' => ['오늘', '힙합', '건대', '가성비'],
                'dress_code' => '캐주얼',
                'entry_condition' => '19세 이상',
                'description' => '건대 KREAM의 금요 힙합 파티. 가성비 최고!',
                'thumbnail' => 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=600&q=80',
                'status' => 'upcoming',
            ],

            // ── 내일 파티 ──
            [
                'club_id' => $clubIds['octagon'] ?? null,
                'name' => 'OCTAGON SATURDAY FEVER',
                'slug' => 'octagon-saturday-fever-' . $today->addDay()->format('Ymd'),
                'event_date' => $today->copy()->addDay()->toDateString(),
                'start_time' => '22:00',
                'end_time' => '07:00',
                'lineup' => 'MARTIN GARRIX (NL) · OCTAGON DJ TEAM',
                'ticket_price_min' => 50000,
                'ticket_price_max' => 80000,
                'genre' => 'EDM',
                'tags' => ['내일', 'EDM', '강남', '내한', '월드스타'],
                'booking_link' => 'https://example.com/ticket/octagon-garrix',
                'dress_code' => '스마트 캐주얼',
                'entry_condition' => '20세 이상 / 신분증 필수',
                'description' => 'MARTIN GARRIX 서울 단독 공연! 옥타곤에서 만나는 세계 최정상 DJ.',
                'thumbnail' => 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=600&q=80',
                'status' => 'upcoming',
            ],
            [
                'club_id' => $clubIds['ellui'] ?? null,
                'name' => 'ELLUI POOL PARTY',
                'slug' => 'ellui-pool-party-' . $today->copy()->addDay()->format('Ymd'),
                'event_date' => $today->copy()->addDay()->toDateString(),
                'start_time' => '15:00',
                'end_time' => '23:00',
                'lineup' => 'DJ KOOL · SUNBEAM · ELLUI RESIDENTS',
                'ticket_price_min' => 40000,
                'ticket_price_max' => 60000,
                'genre' => 'EDM',
                'tags' => ['내일', '풀파티', '강남', '데이파티'],
                'booking_link' => 'https://example.com/ticket/ellui-pool',
                'dress_code' => '수영복/비치웨어',
                'entry_condition' => '20세 이상 / 수영복 필수',
                'description' => 'ELLUI의 시그니처 풀파티! 낮부터 밤까지 즐기는 수영장 EDM 파티.',
                'thumbnail' => 'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?w=600&q=80',
                'status' => 'upcoming',
            ],
            [
                'club_id' => $clubIds['vurt'] ?? null,
                'name' => 'VURT × BEN KLOCK',
                'slug' => 'vurt-ben-klock-' . $today->copy()->addDay()->format('Ymd'),
                'event_date' => $today->copy()->addDay()->toDateString(),
                'start_time' => '23:00',
                'end_time' => '08:00',
                'lineup' => 'BEN KLOCK (Berlin) · VURT RESIDENTS',
                'ticket_price_min' => 25000,
                'ticket_price_max' => 35000,
                'genre' => '테크노',
                'tags' => ['내일', '테크노', '이태원', '베를린'],
                'booking_link' => 'https://example.com/ticket/vurt-klock',
                'dress_code' => '자유',
                'entry_condition' => '20세 이상',
                'description' => '베를린 Berghain의 레지던트 BEN KLOCK이 VURT에 온다!',
                'thumbnail' => 'https://images.unsplash.com/photo-1545128485-c400e7702796?w=600&q=80',
                'status' => 'upcoming',
            ],
            [
                'club_id' => $clubIds['mute-club'] ?? null,
                'name' => 'MUTE AMBIENT SESSION',
                'slug' => 'mute-ambient-' . $today->copy()->addDay()->format('Ymd'),
                'event_date' => $today->copy()->addDay()->toDateString(),
                'start_time' => '23:00',
                'end_time' => '06:00',
                'lineup' => 'VISIBLE CLOAKS · MUTE SOUND COLLECTIVE',
                'ticket_price_min' => 15000,
                'ticket_price_max' => 20000,
                'genre' => '테크노',
                'tags' => ['내일', '앰비언트', '홍대', '실험음악'],
                'dress_code' => '자유',
                'entry_condition' => '19세 이상',
                'description' => 'MUTE의 앰비언트/실험 음악 세션. 깊은 사운드의 밤.',
                'thumbnail' => 'https://images.unsplash.com/photo-1571266028243-e4733b0f0bb0?w=600&q=80',
                'status' => 'upcoming',
            ],
            [
                'club_id' => $clubIds['made-hongdae'] ?? null,
                'name' => 'K-POP PARTY NIGHT',
                'slug' => 'kpop-party-night-' . $today->copy()->addDay()->format('Ymd'),
                'event_date' => $today->copy()->addDay()->toDateString(),
                'start_time' => '21:00',
                'end_time' => '05:00',
                'lineup' => 'DJ KPOP MASTER · MADE RESIDENT DJs',
                'ticket_price_min' => 10000,
                'ticket_price_max' => 15000,
                'genre' => '케이팝',
                'tags' => ['내일', '케이팝', '홍대', '외국인환영'],
                'dress_code' => '캐주얼',
                'entry_condition' => '19세 이상',
                'description' => 'MADE 홍대의 K-POP 파티! BTS, BLACKPINK, NewJeans 히트곡 총출동.',
                'thumbnail' => 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=600&q=80',
                'status' => 'upcoming',
            ],

            // ── 이번 주 파티 ──
            [
                'club_id' => $clubIds['burning-sun'] ?? null,
                'name' => 'NEON NIGHTS',
                'slug' => 'neon-nights-' . $today->copy()->addDays(3)->format('Ymd'),
                'event_date' => $today->copy()->addDays(3)->toDateString(),
                'start_time' => '22:00',
                'end_time' => '06:00',
                'lineup' => 'SKRILLEX (US) · BURNING SUN DJs',
                'ticket_price_min' => 40000,
                'ticket_price_max' => 60000,
                'genre' => 'EDM',
                'tags' => ['이번주', 'EDM', '강남', '내한공연'],
                'booking_link' => 'https://example.com/ticket/neon-nights',
                'dress_code' => '세미 포멀',
                'entry_condition' => '20세 이상',
                'description' => 'SKRILLEX 서울 공연! 강남 BURNING SUN에서 열리는 네온 파티.',
                'thumbnail' => 'https://images.unsplash.com/photo-1574391884720-bbc3740c59d1?w=600&q=80',
                'status' => 'upcoming',
            ],
            [
                'club_id' => $clubIds['le-chamber'] ?? null,
                'name' => 'DEEP HOUSE THERAPY',
                'slug' => 'deep-house-therapy-' . $today->copy()->addDays(3)->format('Ymd'),
                'event_date' => $today->copy()->addDays(3)->toDateString(),
                'start_time' => '22:00',
                'end_time' => '05:00',
                'lineup' => 'KERRI CHANDLER (US) · LE CHAMBER RESIDENTS',
                'ticket_price_min' => 20000,
                'ticket_price_max' => 30000,
                'genre' => '하우스',
                'tags' => ['이번주', '딥하우스', '압구정', '해외DJ'],
                'booking_link' => 'https://example.com/ticket/deep-house-therapy',
                'dress_code' => '스마트 캐주얼',
                'entry_condition' => '20세 이상',
                'description' => '딥하우스의 전설 KERRI CHANDLER가 LE CHAMBER에 옵니다.',
                'thumbnail' => 'https://images.unsplash.com/photo-1566417713940-fe7c737a9ef2?w=600&q=80',
                'status' => 'upcoming',
            ],
            [
                'club_id' => $clubIds['fountain'] ?? null,
                'name' => 'SOUL KITCHEN',
                'slug' => 'soul-kitchen-' . $today->copy()->addDays(4)->format('Ymd'),
                'event_date' => $today->copy()->addDays(4)->toDateString(),
                'start_time' => '21:00',
                'end_time' => '04:00',
                'lineup' => 'DJ SOULSCAPE · PARK HYE JIN · FOUNTAIN CREW',
                'ticket_price_min' => 15000,
                'ticket_price_max' => 20000,
                'genre' => 'R&B',
                'tags' => ['이번주', 'R&B', '소울', '이태원'],
                'dress_code' => '스마트 캐주얼',
                'entry_condition' => '20세 이상',
                'description' => 'FOUNTAIN의 소울 키친 파티. R&B/소울 감성의 밤.',
                'thumbnail' => 'https://images.unsplash.com/photo-1598653222000-6b7b7a552625?w=600&q=80',
                'status' => 'upcoming',
            ],
            [
                'club_id' => $clubIds['warehouse-seongsu'] ?? null,
                'name' => 'WAREHOUSE RAVE',
                'slug' => 'warehouse-rave-' . $today->copy()->addDays(4)->format('Ymd'),
                'event_date' => $today->copy()->addDays(4)->toDateString(),
                'start_time' => '23:00',
                'end_time' => '08:00',
                'lineup' => 'AMELIE LENS (BE) · WAREHOUSE COLLECTIVE',
                'ticket_price_min' => 20000,
                'ticket_price_max' => 30000,
                'genre' => '테크노',
                'tags' => ['이번주', '테크노', '성수', '레이브'],
                'booking_link' => 'https://example.com/ticket/warehouse-rave',
                'dress_code' => '자유',
                'entry_condition' => '20세 이상',
                'description' => '성수 WAREHOUSE의 올나이트 레이브. AMELIE LENS 내한!',
                'thumbnail' => 'https://images.unsplash.com/photo-1545128485-c400e7702796?w=600&q=80',
                'status' => 'upcoming',
            ],
            [
                'club_id' => $clubIds['groove-jongno'] ?? null,
                'name' => 'JAZZ & WINE NIGHT',
                'slug' => 'jazz-wine-night-' . $today->copy()->addDays(5)->format('Ymd'),
                'event_date' => $today->copy()->addDays(5)->toDateString(),
                'start_time' => '20:00',
                'end_time' => '02:00',
                'lineup' => 'YOUN SUN NAH TRIO · SPECIAL GUEST',
                'ticket_price_min' => 15000,
                'ticket_price_max' => 25000,
                'genre' => '재즈',
                'tags' => ['이번주', '재즈', '종로', '라이브'],
                'dress_code' => '스마트 캐주얼',
                'entry_condition' => '20세 이상',
                'description' => 'GROOVE의 재즈 & 와인 나이트. 라이브 재즈와 프리미엄 와인.',
                'thumbnail' => 'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?w=600&q=80',
                'status' => 'upcoming',
            ],
            [
                'club_id' => $clubIds['modeci'] ?? null,
                'name' => 'MODECI R&B LOUNGE',
                'slug' => 'modeci-rnb-lounge-' . $today->copy()->addDays(5)->format('Ymd'),
                'event_date' => $today->copy()->addDays(5)->toDateString(),
                'start_time' => '21:00',
                'end_time' => '04:00',
                'lineup' => 'DJ SOULFUL · MODECI RESIDENTS',
                'ticket_price_min' => 10000,
                'ticket_price_max' => 15000,
                'genre' => 'R&B',
                'tags' => ['이번주', 'R&B', '성수', '라운지'],
                'dress_code' => '자유',
                'entry_condition' => '20세 이상',
                'description' => '성수 MODECI의 R&B 라운지 파티. 차분한 감성의 밤.',
                'thumbnail' => 'https://images.unsplash.com/photo-1566417713940-fe7c737a9ef2?w=600&q=80',
                'status' => 'upcoming',
            ],

            // ── 다음 주 파티 ──
            [
                'club_id' => $clubIds['fabric-seoul'] ?? null,
                'name' => 'FABRIC × NINA KRAVIZ',
                'slug' => 'fabric-nina-kraviz-' . $today->copy()->addDays(7)->format('Ymd'),
                'event_date' => $today->copy()->addDays(7)->toDateString(),
                'start_time' => '23:00',
                'end_time' => '08:00',
                'lineup' => 'NINA KRAVIZ (RU) · FABRIC RESIDENTS',
                'ticket_price_min' => 25000,
                'ticket_price_max' => 40000,
                'genre' => '테크노',
                'tags' => ['다음주', '테크노', '홍대', '내한'],
                'booking_link' => 'https://example.com/ticket/fabric-nina',
                'dress_code' => '자유',
                'entry_condition' => '20세 이상',
                'description' => '테크노 여왕 NINA KRAVIZ의 FABRIC SEOUL 내한 공연!',
                'thumbnail' => 'https://images.unsplash.com/photo-1571266028243-e4733b0f0bb0?w=600&q=80',
                'status' => 'upcoming',
            ],
            [
                'club_id' => $clubIds['cakeshop'] ?? null,
                'name' => 'CAKESHOP × KEITH APE',
                'slug' => 'cakeshop-keith-ape-' . $today->copy()->addDays(8)->format('Ymd'),
                'event_date' => $today->copy()->addDays(8)->toDateString(),
                'start_time' => '22:00',
                'end_time' => '05:00',
                'lineup' => 'KEITH APE · OKASIAN · DJ SMELLS',
                'ticket_price_min' => 20000,
                'ticket_price_max' => 30000,
                'genre' => '힙합',
                'tags' => ['다음주', '힙합', '이태원', '래퍼'],
                'booking_link' => 'https://example.com/ticket/cakeshop-keith',
                'dress_code' => '자유',
                'entry_condition' => '19세 이상',
                'description' => 'KEITH APE & OKASIAN의 CAKESHOP 합동 공연. 잇태원 프리덤!',
                'thumbnail' => 'https://images.unsplash.com/photo-1598653222000-6b7b7a552625?w=600&q=80',
                'status' => 'upcoming',
            ],
            [
                'club_id' => $clubIds['arena-club'] ?? null,
                'name' => 'ARENA × TIËSTO',
                'slug' => 'arena-tiesto-' . $today->copy()->addDays(9)->format('Ymd'),
                'event_date' => $today->copy()->addDays(9)->toDateString(),
                'start_time' => '22:00',
                'end_time' => '06:00',
                'lineup' => 'TIËSTO (NL) · ARENA RESIDENTS',
                'ticket_price_min' => 50000,
                'ticket_price_max' => 80000,
                'genre' => 'EDM',
                'tags' => ['다음주', 'EDM', '강남', '월드스타'],
                'booking_link' => 'https://example.com/ticket/arena-tiesto',
                'dress_code' => '스마트 캐주얼',
                'entry_condition' => '20세 이상',
                'description' => 'EDM의 전설 TIËSTO가 ARENA에 온다! 올해 최대 규모 파티.',
                'thumbnail' => 'https://images.unsplash.com/photo-1574391884720-bbc3740c59d1?w=600&q=80',
                'status' => 'upcoming',
            ],
            [
                'club_id' => $clubIds['mass-gangnam'] ?? null,
                'name' => 'MASS HIP-HOP FESTIVAL',
                'slug' => 'mass-hiphop-fest-' . $today->copy()->addDays(10)->format('Ymd'),
                'event_date' => $today->copy()->addDays(10)->toDateString(),
                'start_time' => '21:00',
                'end_time' => '05:00',
                'lineup' => 'BEWHY · CHANGMO · GIRIBOY · pH-1',
                'ticket_price_min' => 20000,
                'ticket_price_max' => 30000,
                'genre' => '힙합',
                'tags' => ['다음주', '힙합', '강남', '페스티벌'],
                'booking_link' => 'https://example.com/ticket/mass-hiphop',
                'dress_code' => '캐주얼',
                'entry_condition' => '19세 이상',
                'description' => 'MASS 강남의 힙합 페스티벌! 국내 최정상 래퍼 4인 총출동.',
                'thumbnail' => 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=600&q=80',
                'status' => 'upcoming',
            ],
            [
                'club_id' => $clubIds['soap-seoul'] ?? null,
                'name' => 'SOAP × CHARLOTTE DE WITTE',
                'slug' => 'soap-charlotte-' . $today->copy()->addDays(12)->format('Ymd'),
                'event_date' => $today->copy()->addDays(12)->toDateString(),
                'start_time' => '23:00',
                'end_time' => '08:00',
                'lineup' => 'CHARLOTTE DE WITTE (BE) · SOAP RESIDENTS',
                'ticket_price_min' => 25000,
                'ticket_price_max' => 35000,
                'genre' => '테크노',
                'tags' => ['다음주', '테크노', '이태원', '다크'],
                'booking_link' => 'https://example.com/ticket/soap-charlotte',
                'dress_code' => '블랙 계열',
                'entry_condition' => '20세 이상',
                'description' => '테크노 신의 새로운 아이콘 CHARLOTTE DE WITTE가 SOAP에 온다!',
                'thumbnail' => 'https://images.unsplash.com/photo-1545128485-c400e7702796?w=600&q=80',
                'status' => 'upcoming',
            ],
            [
                'club_id' => $clubIds['playground-kondae'] ?? null,
                'name' => 'PLAYGROUND SUMMER FEST',
                'slug' => 'playground-summer-' . $today->copy()->addDays(10)->format('Ymd'),
                'event_date' => $today->copy()->addDays(10)->toDateString(),
                'start_time' => '20:00',
                'end_time' => '05:00',
                'lineup' => 'DJ HANMIN · K-POP REMIX CREW · PLAYGROUND DJs',
                'ticket_price_min' => 10000,
                'ticket_price_max' => 15000,
                'genre' => 'EDM',
                'tags' => ['다음주', 'EDM', '건대', '여름파티'],
                'dress_code' => '캐주얼',
                'entry_condition' => '19세 이상',
                'description' => '건대 PLAYGROUND의 여름 맞이 EDM 페스티벌. 가성비 최고!',
                'thumbnail' => 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=600&q=80',
                'status' => 'upcoming',
            ],
            [
                'club_id' => $clubIds['pulse-club'] ?? null,
                'name' => 'PULSE TRANCE NIGHT',
                'slug' => 'pulse-trance-' . $today->copy()->addDays(11)->format('Ymd'),
                'event_date' => $today->copy()->addDays(11)->toDateString(),
                'start_time' => '22:00',
                'end_time' => '05:00',
                'lineup' => 'ABOVE & BEYOND (UK) · PULSE RESIDENTS',
                'ticket_price_min' => 20000,
                'ticket_price_max' => 30000,
                'genre' => 'EDM',
                'tags' => ['다음주', '트랜스', '종로', '내한'],
                'booking_link' => 'https://example.com/ticket/pulse-trance',
                'dress_code' => '캐주얼',
                'entry_condition' => '20세 이상',
                'description' => '트랜스의 전설 ABOVE & BEYOND이 종로 PULSE에서 공연합니다!',
                'thumbnail' => 'https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?w=600&q=80',
                'status' => 'upcoming',
            ],
            [
                'club_id' => $clubIds['mikes-cabin'] ?? null,
                'name' => 'INDIE ROCK SHOWCASE',
                'slug' => 'indie-rock-showcase-' . $today->copy()->addDays(8)->format('Ymd'),
                'event_date' => $today->copy()->addDays(8)->toDateString(),
                'start_time' => '20:00',
                'end_time' => '03:00',
                'lineup' => 'HYUKOH · SE SO NEON · SILICA GEL',
                'ticket_price_min' => 15000,
                'ticket_price_max' => 25000,
                'genre' => '록',
                'tags' => ['다음주', '인디록', '신촌', '라이브'],
                'booking_link' => 'https://example.com/ticket/indie-showcase',
                'dress_code' => '자유',
                'entry_condition' => '19세 이상',
                'description' => '신촌 MIKE\'S CABIN의 인디록 쇼케이스. 혁오, 새소년, 실리카겔 출연!',
                'thumbnail' => 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=600&q=80',
                'status' => 'upcoming',
            ],
        ];

        foreach ($parties as $party) {
            if ($party['club_id'] !== null) {
                Party::create($party);
            }
        }
    }
}
