<?php

namespace Database\Seeders;

use App\Models\Club;
use Illuminate\Database\Seeder;

class AdditionalClubSeeder extends Seeder
{
    public function run(): void
    {
        $clubs = [
            // ── 홍대 ──
            [
                'name' => 'VENUE',
                'slug' => 'venue-hongdae',
                'area' => '홍대',
                'genre' => 'EDM',
                'subgenre' => '하우스',
                'vibe' => '에너지틱',
                'open_time' => '22:00',
                'close_time' => '06:00',
                'entry_fee_min' => 15000,
                'entry_fee_max' => 25000,
                'foreigner_allowed' => true,
                'dress_code' => '캐주얼',
                'dress_code_detail' => '편안한 복장 OK. 슬리퍼 불가.',
                'lat' => 37.5537,
                'lng' => 126.9215,
                'address' => '서울 마포구 잔다리로 50',
                'instagram' => '@venue_hongdae',
                'rating_avg' => 4.1,
                'rating_count' => 167,
                'rating_summary' => 'EDM 입문자에게 최고. 조명 연출이 화려하고 분위기 잘 띄워줌.',
                'description' => '홍대 메인 스트릿 근처의 EDM/하우스 클럽. 화려한 LED 조명과 에너지 넘치는 분위기.',
                'thumbnail' => 'https://images.unsplash.com/photo-1571266028243-e4733b0f0bb0?w=600&q=80',
                'tags' => ['EDM', '홍대', '조명맛집', '입문자추천'],
                'is_active' => true,
            ],
            [
                'name' => 'NB CLUB',
                'slug' => 'nb-club',
                'area' => '홍대',
                'genre' => '힙합',
                'subgenre' => 'R&B',
                'vibe' => '파티',
                'open_time' => '21:00',
                'close_time' => '05:00',
                'entry_fee_min' => 10000,
                'entry_fee_max' => 20000,
                'foreigner_allowed' => true,
                'dress_code' => '캐주얼',
                'dress_code_detail' => '자유롭게 입장 가능. 슬리퍼 불가.',
                'lat' => 37.5548,
                'lng' => 126.9220,
                'address' => '서울 마포구 와우산로21길 19-3',
                'instagram' => '@nb_club_seoul',
                'rating_avg' => 3.9,
                'rating_count' => 223,
                'rating_summary' => '홍대 원조 힙합 클럽. 가성비 좋고 항상 사람 많음.',
                'description' => '홍대 클럽 문화의 시작점. 오랜 역사를 가진 힙합/R&B 클럽.',
                'thumbnail' => 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=600&q=80',
                'tags' => ['힙합', '홍대', '가성비', '원조'],
                'is_active' => true,
            ],
            [
                'name' => 'MUTE CLUB',
                'slug' => 'mute-club',
                'area' => '홍대',
                'genre' => '테크노',
                'subgenre' => '앰비언트',
                'vibe' => '언더그라운드',
                'open_time' => '23:00',
                'close_time' => '07:00',
                'entry_fee_min' => 15000,
                'entry_fee_max' => 20000,
                'foreigner_allowed' => true,
                'dress_code' => '자유',
                'dress_code_detail' => '편안한 복장. 다크 계열 선호.',
                'lat' => 37.5533,
                'lng' => 126.9208,
                'address' => '서울 마포구 어울마당로 120',
                'instagram' => '@muteclub_seoul',
                'rating_avg' => 4.4,
                'rating_count' => 95,
                'rating_summary' => '사운드에 진심인 공간. 소규모라 몰입감 최고.',
                'description' => '홍대 골목의 소규모 테크노/앰비언트 클럽. 사운드 퀄리티에 집중하는 공간.',
                'thumbnail' => 'https://images.unsplash.com/photo-1545128485-c400e7702796?w=600&q=80',
                'tags' => ['테크노', '앰비언트', '소규모', '사운드맛집'],
                'is_active' => true,
            ],
            [
                'name' => 'MADE HONGDAE',
                'slug' => 'made-hongdae',
                'area' => '홍대',
                'genre' => '케이팝',
                'subgenre' => '힙합',
                'vibe' => '트렌디',
                'open_time' => '21:00',
                'close_time' => '05:00',
                'entry_fee_min' => 10000,
                'entry_fee_max' => 15000,
                'foreigner_allowed' => true,
                'dress_code' => '캐주얼',
                'dress_code_detail' => '자유로운 드레스코드.',
                'lat' => 37.5551,
                'lng' => 126.9235,
                'address' => '서울 마포구 홍익로 20',
                'instagram' => '@made_hongdae',
                'rating_avg' => 4.0,
                'rating_count' => 310,
                'rating_summary' => '케이팝 위주라 외국인 관광객에게 인기. 분위기 가볍고 재밌음.',
                'description' => '케이팝과 최신 힙합을 중심으로 한 홍대의 인기 클럽. 외국인 관광객도 많이 찾는 곳.',
                'thumbnail' => 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=600&q=80',
                'tags' => ['케이팝', '관광객', '홍대', '트렌디'],
                'is_active' => true,
            ],

            // ── 강남 ──
            [
                'name' => 'BURNING SUN',
                'slug' => 'burning-sun',
                'area' => '강남',
                'genre' => 'EDM',
                'subgenre' => '프로그레시브',
                'vibe' => '프리미엄',
                'open_time' => '22:00',
                'close_time' => '06:00',
                'entry_fee_min' => 25000,
                'entry_fee_max' => 40000,
                'foreigner_allowed' => true,
                'dress_code' => '세미 포멀',
                'dress_code_detail' => '정장 또는 드레시한 의상 권장. 운동화/슬리퍼 입장 불가.',
                'lat' => 37.5087,
                'lng' => 127.0632,
                'address' => '서울 강남구 역삼동 823-8',
                'instagram' => '@burningsun_gangnam',
                'rating_avg' => 4.2,
                'rating_count' => 445,
                'rating_summary' => '강남 프리미엄 EDM의 대표. 인테리어 고급스럽고 라인업이 화려.',
                'description' => '강남 역삼 지역의 프리미엄 EDM 클럽. 화려한 인테리어와 최고급 사운드 시스템.',
                'thumbnail' => 'https://images.unsplash.com/photo-1574391884720-bbc3740c59d1?w=600&q=80',
                'tags' => ['EDM', '프리미엄', '강남', 'VIP'],
                'is_active' => true,
            ],
            [
                'name' => 'MASS GANGNAM',
                'slug' => 'mass-gangnam',
                'area' => '강남',
                'genre' => '힙합',
                'subgenre' => 'R&B',
                'vibe' => '캐주얼',
                'open_time' => '22:00',
                'close_time' => '06:00',
                'entry_fee_min' => 15000,
                'entry_fee_max' => 25000,
                'foreigner_allowed' => true,
                'dress_code' => '캐주얼',
                'dress_code_detail' => '편안한 복장 가능. 기본적인 드레스코드 적용.',
                'lat' => 37.5010,
                'lng' => 127.0265,
                'address' => '서울 강남구 강남대로 110',
                'instagram' => '@mass_gangnam',
                'rating_avg' => 4.0,
                'rating_count' => 187,
                'rating_summary' => '강남 힙합씬의 핫플. 가성비 대비 만족도 좋음.',
                'description' => '강남의 힙합/R&B 클럽. 접근성이 좋고 분위기가 편안함.',
                'thumbnail' => 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=600&q=80',
                'tags' => ['힙합', 'R&B', '강남', '접근성좋음'],
                'is_active' => true,
            ],
            [
                'name' => 'ELLUI',
                'slug' => 'ellui',
                'area' => '강남',
                'genre' => 'EDM',
                'subgenre' => '팝',
                'vibe' => '럭셔리',
                'open_time' => '22:00',
                'close_time' => '06:00',
                'entry_fee_min' => 30000,
                'entry_fee_max' => 50000,
                'foreigner_allowed' => true,
                'dress_code' => '세미 포멀',
                'dress_code_detail' => '정장 또는 드레시한 의상 필수. 스니커즈 불가.',
                'lat' => 37.5123,
                'lng' => 127.0580,
                'address' => '서울 강남구 논현로 172길 23',
                'instagram' => '@ellui_seoul',
                'rating_avg' => 4.5,
                'rating_count' => 378,
                'rating_summary' => '국내 최대 규모 럭셔리 클럽. 수영장 파티 등 특별 이벤트 유명.',
                'description' => '강남의 초대형 럭셔리 클럽. 수영장, VIP룸 등 다양한 공간을 보유한 복합 나이트 공간.',
                'thumbnail' => 'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?w=600&q=80',
                'tags' => ['럭셔리', '대형클럽', '수영장파티', 'VIP'],
                'is_active' => true,
            ],

            // ── 이태원 ──
            [
                'name' => 'CONTRA',
                'slug' => 'contra',
                'area' => '이태원',
                'genre' => '하우스',
                'subgenre' => '디스코',
                'vibe' => '인디',
                'open_time' => '22:00',
                'close_time' => '06:00',
                'entry_fee_min' => 10000,
                'entry_fee_max' => 15000,
                'foreigner_allowed' => true,
                'dress_code' => '자유',
                'dress_code_detail' => '완전한 자유. 개성적일수록 환영.',
                'lat' => 37.5345,
                'lng' => 126.9940,
                'address' => '서울 용산구 이태원로27가길 40',
                'instagram' => '@contra_itaewon',
                'rating_avg' => 4.3,
                'rating_count' => 142,
                'rating_summary' => '이태원 감성 하우스/디스코. 자유로운 분위기, 다국적 손님.',
                'description' => '이태원의 인디 하우스/디스코 클럽. 다양한 국적의 사람들이 자유롭게 어울리는 공간.',
                'thumbnail' => 'https://images.unsplash.com/photo-1566417713940-fe7c737a9ef2?w=600&q=80',
                'tags' => ['하우스', '디스코', '이태원', '자유로운'],
                'is_active' => true,
            ],
            [
                'name' => 'FOUNTAIN',
                'slug' => 'fountain',
                'area' => '이태원',
                'genre' => 'R&B',
                'subgenre' => '소울',
                'vibe' => '무드',
                'open_time' => '21:00',
                'close_time' => '05:00',
                'entry_fee_min' => 10000,
                'entry_fee_max' => 20000,
                'foreigner_allowed' => true,
                'dress_code' => '스마트 캐주얼',
                'dress_code_detail' => '깔끔한 복장. 반바지/슬리퍼 불가.',
                'lat' => 37.5355,
                'lng' => 126.9930,
                'address' => '서울 용산구 이태원로 190',
                'instagram' => '@fountain_itaewon',
                'rating_avg' => 4.2,
                'rating_count' => 118,
                'rating_summary' => 'R&B/소울 감성 공간. 무드 있고 대화가 가능한 볼륨.',
                'description' => '이태원의 R&B/소울 바 겸 클럽. 분위기 있는 공간에서 음악을 즐길 수 있는 곳.',
                'thumbnail' => 'https://images.unsplash.com/photo-1598653222000-6b7b7a552625?w=600&q=80',
                'tags' => ['R&B', '소울', '이태원', '무드'],
                'is_active' => true,
            ],
            [
                'name' => 'VURT',
                'slug' => 'vurt',
                'area' => '이태원',
                'genre' => '테크노',
                'subgenre' => '일렉트로닉',
                'vibe' => '실험적',
                'open_time' => '23:00',
                'close_time' => '08:00',
                'entry_fee_min' => 15000,
                'entry_fee_max' => 25000,
                'foreigner_allowed' => true,
                'dress_code' => '자유',
                'dress_code_detail' => '자유로운 복장.',
                'lat' => 37.5340,
                'lng' => 126.9945,
                'address' => '서울 용산구 녹사평대로 234',
                'instagram' => '@vurt_seoul',
                'rating_avg' => 4.6,
                'rating_count' => 203,
                'rating_summary' => '실험적 일렉트로닉 음악의 성지. 해외 DJ 라인업 퀄리티 최상급.',
                'description' => '이태원의 실험적 일렉트로닉 클럽. 글로벌 언더그라운드 씬과 직접 연결된 프로그래밍.',
                'thumbnail' => 'https://images.unsplash.com/photo-1571266028243-e4733b0f0bb0?w=600&q=80',
                'tags' => ['테크노', '실험적', '해외DJ', '언더그라운드'],
                'is_active' => true,
            ],

            // ── 압구정 ──
            [
                'name' => 'GOLDEN GOOSE',
                'slug' => 'golden-goose',
                'area' => '압구정',
                'genre' => '힙합',
                'subgenre' => 'R&B',
                'vibe' => '럭셔리',
                'open_time' => '22:00',
                'close_time' => '06:00',
                'entry_fee_min' => 25000,
                'entry_fee_max' => 40000,
                'foreigner_allowed' => true,
                'dress_code' => '세미 포멀',
                'dress_code_detail' => '드레시한 의상 권장. 명품 코디 환영.',
                'lat' => 37.5275,
                'lng' => 127.0398,
                'address' => '서울 강남구 압구정로 162',
                'instagram' => '@goldengoose_apgu',
                'rating_avg' => 4.3,
                'rating_count' => 156,
                'rating_summary' => '압구정 셀럽 클럽. 분위기 고급스럽고 힙합 선곡 좋음.',
                'description' => '압구정의 럭셔리 힙합 클럽. 셀럽들이 자주 찾는 프리미엄 공간.',
                'thumbnail' => 'https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?w=600&q=80',
                'tags' => ['힙합', '럭셔리', '셀럽', '압구정'],
                'is_active' => true,
            ],
            [
                'name' => 'LE CHAMBER',
                'slug' => 'le-chamber',
                'area' => '압구정',
                'genre' => '하우스',
                'subgenre' => '딥하우스',
                'vibe' => '시크',
                'open_time' => '22:00',
                'close_time' => '05:00',
                'entry_fee_min' => 20000,
                'entry_fee_max' => 30000,
                'foreigner_allowed' => true,
                'dress_code' => '스마트 캐주얼',
                'dress_code_detail' => '깔끔하고 세련된 복장.',
                'lat' => 37.5268,
                'lng' => 127.0410,
                'address' => '서울 강남구 압구정로 170',
                'instagram' => '@lechamber_seoul',
                'rating_avg' => 4.4,
                'rating_count' => 98,
                'rating_summary' => '딥하우스 매니아 필수 코스. 소규모지만 사운드 퀄리티 최고.',
                'description' => '압구정의 시크한 딥하우스 라운지. 소규모 공간에서 깊은 음악을 즐기는 공간.',
                'thumbnail' => 'https://images.unsplash.com/photo-1566417713940-fe7c737a9ef2?w=600&q=80',
                'tags' => ['딥하우스', '시크', '소규모', '압구정'],
                'is_active' => true,
            ],

            // ── 건대 ──
            [
                'name' => 'KREAM',
                'slug' => 'kream-club',
                'area' => '건대',
                'genre' => '힙합',
                'subgenre' => '케이팝',
                'vibe' => '캐주얼',
                'open_time' => '21:00',
                'close_time' => '05:00',
                'entry_fee_min' => 10000,
                'entry_fee_max' => 15000,
                'foreigner_allowed' => true,
                'dress_code' => '캐주얼',
                'dress_code_detail' => '편안한 복장 OK.',
                'lat' => 37.5404,
                'lng' => 127.0688,
                'address' => '서울 광진구 아차산로 243',
                'instagram' => '@kream_club',
                'rating_avg' => 3.8,
                'rating_count' => 276,
                'rating_summary' => '건대 대학가 클럽. 가격 저렴하고 대학생이 많아 분위기 젊음.',
                'description' => '건대입구역 인근의 대학가 클럽. 합리적인 가격에 즐길 수 있는 힙합/케이팝 파티.',
                'thumbnail' => 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=600&q=80',
                'tags' => ['힙합', '케이팝', '건대', '대학생'],
                'is_active' => true,
            ],
            [
                'name' => 'PLAYGROUND',
                'slug' => 'playground-kondae',
                'area' => '건대',
                'genre' => 'EDM',
                'subgenre' => '팝',
                'vibe' => '파티',
                'open_time' => '22:00',
                'close_time' => '05:00',
                'entry_fee_min' => 10000,
                'entry_fee_max' => 20000,
                'foreigner_allowed' => true,
                'dress_code' => '캐주얼',
                'dress_code_detail' => '자유로운 복장.',
                'lat' => 37.5410,
                'lng' => 127.0695,
                'address' => '서울 광진구 능동로 110',
                'instagram' => '@playground_kondae',
                'rating_avg' => 3.9,
                'rating_count' => 198,
                'rating_summary' => 'EDM 입문 클럽. 분위기 가볍고 재밌음. 가격도 착함.',
                'description' => '건대의 캐주얼 EDM/팝 클럽. 가벼운 파티 분위기로 처음 오는 분들에게 좋은 곳.',
                'thumbnail' => 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=600&q=80',
                'tags' => ['EDM', '팝', '건대', '가성비'],
                'is_active' => true,
            ],

            // ── 신촌 ──
            [
                'name' => 'MIKE\'S CABIN',
                'slug' => 'mikes-cabin',
                'area' => '신촌',
                'genre' => '록',
                'subgenre' => '인디',
                'vibe' => '라이브',
                'open_time' => '20:00',
                'close_time' => '04:00',
                'entry_fee_min' => 10000,
                'entry_fee_max' => 15000,
                'foreigner_allowed' => true,
                'dress_code' => '자유',
                'dress_code_detail' => '완전 자유.',
                'lat' => 37.5563,
                'lng' => 126.9370,
                'address' => '서울 서대문구 연세로 30',
                'instagram' => '@mikescabin_sinchon',
                'rating_avg' => 4.1,
                'rating_count' => 132,
                'rating_summary' => '신촌 라이브 음악 명소. 인디밴드 공연과 DJ 세트 병행.',
                'description' => '신촌의 라이브 록/인디 클럽. 밴드 공연과 DJ 파티가 함께하는 독특한 공간.',
                'thumbnail' => 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=600&q=80',
                'tags' => ['록', '인디', '라이브', '신촌'],
                'is_active' => true,
            ],
            [
                'name' => 'VENT',
                'slug' => 'vent-sinchon',
                'area' => '신촌',
                'genre' => '힙합',
                'subgenre' => '팝',
                'vibe' => '캐주얼',
                'open_time' => '21:00',
                'close_time' => '05:00',
                'entry_fee_min' => 8000,
                'entry_fee_max' => 15000,
                'foreigner_allowed' => true,
                'dress_code' => '캐주얼',
                'dress_code_detail' => '편안한 복장.',
                'lat' => 37.5570,
                'lng' => 126.9365,
                'address' => '서울 서대문구 신촌역로 25',
                'instagram' => '@vent_sinchon',
                'rating_avg' => 3.7,
                'rating_count' => 205,
                'rating_summary' => '신촌 가성비 최고 클럽. 대학생 모임에 최적.',
                'description' => '신촌의 캐주얼 힙합 클럽. 합리적인 가격으로 파티를 즐길 수 있는 곳.',
                'thumbnail' => 'https://images.unsplash.com/photo-1598653222000-6b7b7a552625?w=600&q=80',
                'tags' => ['힙합', '가성비', '신촌', '대학생'],
                'is_active' => true,
            ],

            // ── 성수 ──
            [
                'name' => 'MODECI',
                'slug' => 'modeci',
                'area' => '성수',
                'genre' => 'R&B',
                'subgenre' => '소울',
                'vibe' => '힙',
                'open_time' => '21:00',
                'close_time' => '04:00',
                'entry_fee_min' => 10000,
                'entry_fee_max' => 15000,
                'foreigner_allowed' => true,
                'dress_code' => '자유',
                'dress_code_detail' => '성수 감성에 맞는 힙한 코디 환영.',
                'lat' => 37.5440,
                'lng' => 127.0560,
                'address' => '서울 성동구 서울숲길 44',
                'instagram' => '@modeci_seongsu',
                'rating_avg' => 4.2,
                'rating_count' => 76,
                'rating_summary' => 'R&B/소울 감성 라운지. 성수 핫플 중 가장 분위기 있음.',
                'description' => '성수동 서울숲 근처의 R&B/소울 라운지 클럽. 트렌디한 성수 감성.',
                'thumbnail' => 'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?w=600&q=80',
                'tags' => ['R&B', '소울', '성수', '라운지'],
                'is_active' => true,
            ],
            [
                'name' => 'WAREHOUSE',
                'slug' => 'warehouse-seongsu',
                'area' => '성수',
                'genre' => '테크노',
                'subgenre' => '하우스',
                'vibe' => '인더스트리얼',
                'open_time' => '23:00',
                'close_time' => '07:00',
                'entry_fee_min' => 15000,
                'entry_fee_max' => 20000,
                'foreigner_allowed' => true,
                'dress_code' => '자유',
                'dress_code_detail' => '자유. 다크 톤 선호.',
                'lat' => 37.5450,
                'lng' => 127.0570,
                'address' => '서울 성동구 성수이로7길 15',
                'instagram' => '@warehouse_seongsu',
                'rating_avg' => 4.3,
                'rating_count' => 67,
                'rating_summary' => '성수 공장 개조 테크노 공간. 인더스트리얼 분위기가 독보적.',
                'description' => '성수동 옛 공장을 개조한 테크노/하우스 클럽. 인더스트리얼 인테리어가 특징.',
                'thumbnail' => 'https://images.unsplash.com/photo-1545128485-c400e7702796?w=600&q=80',
                'tags' => ['테크노', '하우스', '인더스트리얼', '성수'],
                'is_active' => true,
            ],

            // ── 종로 ──
            [
                'name' => 'GROOVE',
                'slug' => 'groove-jongno',
                'area' => '종로',
                'genre' => '재즈',
                'subgenre' => '소울',
                'vibe' => '클래식',
                'open_time' => '20:00',
                'close_time' => '03:00',
                'entry_fee_min' => 0,
                'entry_fee_max' => 10000,
                'foreigner_allowed' => true,
                'dress_code' => '스마트 캐주얼',
                'dress_code_detail' => '깔끔한 캐주얼.',
                'lat' => 37.5720,
                'lng' => 126.9890,
                'address' => '서울 종로구 종로 30',
                'instagram' => '@groove_jongno',
                'rating_avg' => 4.4,
                'rating_count' => 88,
                'rating_summary' => '종로 재즈 바의 정석. 라이브 연주 퀄리티 높음. 분위기 최고.',
                'description' => '종로의 정통 재즈/소울 바. 라이브 연주와 함께 칵테일을 즐기는 클래식한 공간.',
                'thumbnail' => 'https://images.unsplash.com/photo-1566417713940-fe7c737a9ef2?w=600&q=80',
                'tags' => ['재즈', '소울', '라이브', '종로'],
                'is_active' => true,
            ],
            [
                'name' => 'PULSE CLUB',
                'slug' => 'pulse-club',
                'area' => '종로',
                'genre' => 'EDM',
                'subgenre' => '트랜스',
                'vibe' => '에너지틱',
                'open_time' => '22:00',
                'close_time' => '05:00',
                'entry_fee_min' => 10000,
                'entry_fee_max' => 20000,
                'foreigner_allowed' => true,
                'dress_code' => '캐주얼',
                'dress_code_detail' => '자유로운 복장.',
                'lat' => 37.5710,
                'lng' => 126.9885,
                'address' => '서울 종로구 관철동 57',
                'instagram' => '@pulse_jongno',
                'rating_avg' => 3.9,
                'rating_count' => 145,
                'rating_summary' => '종로 EDM/트랜스 클럽. 직장인 모임에 좋고 접근성 최고.',
                'description' => '종로 중심부의 EDM/트랜스 클럽. 직장인들의 퇴근 후 파티 명소.',
                'thumbnail' => 'https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?w=600&q=80',
                'tags' => ['EDM', '트랜스', '종로', '직장인'],
                'is_active' => true,
            ],
        ];

        foreach ($clubs as $club) {
            Club::create($club);
        }
    }
}
