<?php

namespace App\Support;

use Carbon\CarbonImmutable;
use Carbon\CarbonInterface;

class CuratedNightlifeData
{
    /**
     * Manually verified on 2026-04-22 against a mix of official sites,
     * Resident Advisor, government tourism pages, Trip.com, Tripadvisor,
     * Waze and current directory listings.
     */
    public static function clubs(): array
    {
        return [
            [
                'name' => '클럽 아우라',
                'slug' => 'club-aura',
                'area' => '홍대',
                'genre' => 'EDM',
                'subgenre' => '힙합',
                'vibe' => '대형',
                'open_time' => '22:00',
                'close_time' => '06:00',
                'entry_fee_min' => 10000,
                'entry_fee_max' => 15000,
                'foreigner_allowed' => true,
                'dress_code' => '캐주얼',
                'dress_code_detail' => '편안한 복장 가능. 슬리퍼는 피하는 편이 안전합니다.',
                'lat' => 37.5543000,
                'lng' => 126.9218000,
                'address' => '서울 마포구 서교동 364-24',
                'instagram' => '@clubauracokr',
                'rating_avg' => 4.0,
                'rating_count' => 342,
                'rating_summary' => '홍대 메인 스트리트에서 접근이 쉽고 EDM과 힙합 수요를 동시에 흡수하는 대형 클럽.',
                'description' => '홍대에서 가장 대중적인 대형 클럽 중 하나입니다. 메인룸은 EDM 중심, 서브룸은 힙합 위주로 운영되는 날이 많아 처음 방문하는 사용자에게도 설명하기 쉬운 편입니다.',
                'short_description' => '홍대 대형 EDM·힙합 클럽.',
                'intro_title' => '홍대에서 무난하게 인원 모으기 좋은 대형 클럽',
                'guide_text' => '주말 피크 타임은 자정 전후입니다. 외국인 방문 비율이 높고, 초행 손님도 진입 장벽이 낮은 편입니다.',
                'highlight_tags' => ['대형', 'EDM', '힙합', '외국인 OK'],
                'thumbnail' => 'https://images.unsplash.com/photo-1571266028243-e4733b0f0bb0?w=600&q=80',
                'tags' => ['EDM', '힙합', '홍대', '대형클럽'],
                'is_active' => true,
            ],
            [
                'name' => 'NB2',
                'slug' => 'nb2',
                'area' => '홍대',
                'genre' => '힙합',
                'subgenre' => 'R&B',
                'vibe' => '파티',
                'open_time' => '22:00',
                'close_time' => '06:00',
                'entry_fee_min' => 10000,
                'entry_fee_max' => 15000,
                'foreigner_allowed' => true,
                'dress_code' => '캐주얼',
                'dress_code_detail' => '편한 복장 가능. 슬리퍼는 제한될 수 있습니다.',
                'lat' => 37.5548000,
                'lng' => 126.9222000,
                'address' => '서울 마포구 와우산로 72',
                'instagram' => '@clubnb_official',
                'rating_avg' => 3.9,
                'rating_count' => 287,
                'rating_summary' => '홍대 힙합 입문자 유입이 많은 대표적인 스테디셀러 클럽.',
                'description' => '홍대 힙합 씬에서 가장 인지도가 높은 이름 중 하나입니다. 과하게 언더그라운드하지 않아 관광객과 초행 손님이 많이 찾는 편입니다.',
                'short_description' => '홍대 대표 힙합 클럽.',
                'intro_title' => '힙합 위주로 가볍게 시작하기 좋은 홍대 스테디셀러',
                'guide_text' => '대기열이 길어질 수 있어 주말에는 11시 이전 입장 안내가 유리합니다.',
                'highlight_tags' => ['힙합', 'R&B', '홍대', '입문자'],
                'thumbnail' => 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=600&q=80',
                'tags' => ['힙합', 'R&B', '홍대', '원조'],
                'is_active' => true,
            ],
            [
                'name' => '오션',
                'slug' => 'ocean',
                'area' => '홍대',
                'genre' => 'EDM',
                'subgenre' => '팝',
                'vibe' => '에너지틱',
                'open_time' => '22:00',
                'close_time' => '06:00',
                'entry_fee_min' => 10000,
                'entry_fee_max' => 15000,
                'foreigner_allowed' => true,
                'dress_code' => '캐주얼',
                'dress_code_detail' => '편안한 복장 위주로 안내 가능합니다.',
                'lat' => 37.5535000,
                'lng' => 126.9210000,
                'address' => '서울 마포구 잔다리로 6 지하2층',
                'instagram' => '@ocean_hongdae',
                'rating_avg' => 3.8,
                'rating_count' => 198,
                'rating_summary' => '홍대에서 비교적 편하게 들어갈 수 있는 대중형 EDM 클럽.',
                'description' => '매스마켓 성격이 강한 홍대 EDM 클럽입니다. 복잡한 설명보다 접근성과 가격 안정성이 장점인 곳으로 소개하기 좋습니다.',
                'short_description' => '홍대 대중형 EDM 클럽.',
                'intro_title' => '가볍게 EDM 분위기 타기 좋은 홍대 선택지',
                'guide_text' => '대형 언더그라운드 클럽보다는 접근성이 중요한 손님에게 맞습니다.',
                'highlight_tags' => ['EDM', '홍대', '대중형', '입문자'],
                'thumbnail' => 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=600&q=80',
                'tags' => ['EDM', '홍대', '매일영업', '입문자추천'],
                'is_active' => true,
            ],
            [
                'name' => '버뮤다',
                'slug' => 'bermuda',
                'area' => '홍대',
                'genre' => 'EDM',
                'subgenre' => '힙합',
                'vibe' => '파티',
                'open_time' => '22:00',
                'close_time' => '07:00',
                'entry_fee_min' => 10000,
                'entry_fee_max' => 15000,
                'foreigner_allowed' => true,
                'dress_code' => '캐주얼',
                'dress_code_detail' => '편안한 복장 가능. 과도한 비치웨어는 피하는 편이 좋습니다.',
                'lat' => 37.5540000,
                'lng' => 126.9215000,
                'address' => '서울 마포구 와우산로 70 지하1,2층',
                'instagram' => '@bermuda_hongdae',
                'rating_avg' => 3.9,
                'rating_count' => 215,
                'rating_summary' => '홍대 메인 동선에 있고 층 분리가 되어 회전율이 좋은 파티형 클럽.',
                'description' => '홍대 클럽 거리 한복판에 있어 1차 이동 후 2차로 유입시키기 쉽습니다. 지하 2개 층 구조라 EDM과 힙합 수요를 함께 흡수하기 좋습니다.',
                'short_description' => '홍대 클럽거리 중심 2개 층 클럽.',
                'intro_title' => '이동 동선이 편한 홍대 메인 스트리트형 클럽',
                'guide_text' => '초반보다 심야 시간대에 유입이 몰리는 편입니다.',
                'highlight_tags' => ['홍대', '2개층', 'EDM', '힙합'],
                'thumbnail' => 'https://images.unsplash.com/photo-1574391884720-bbc3740c59d1?w=600&q=80',
                'tags' => ['EDM', '힙합', '홍대', '2층규모'],
                'is_active' => true,
            ],
            [
                'name' => '메이드 홍대',
                'slug' => 'made-hongdae',
                'area' => '홍대',
                'genre' => '힙합',
                'subgenre' => 'EDM',
                'vibe' => '캐주얼',
                'open_time' => '22:00',
                'close_time' => '07:30',
                'entry_fee_min' => 10000,
                'entry_fee_max' => 15000,
                'foreigner_allowed' => true,
                'dress_code' => '캐주얼',
                'dress_code_detail' => '과하게 차려입을 필요 없이 자유로운 편입니다.',
                'lat' => 37.5536000,
                'lng' => 126.9211000,
                'address' => '서울 마포구 잔다리로 5 B1',
                'instagram' => '@made_hongdae',
                'rating_avg' => 3.8,
                'rating_count' => 176,
                'rating_summary' => '주말 위주 유입이 많고 가격 부담이 상대적으로 낮은 홍대 클럽.',
                'description' => '메이드 홍대는 금요일과 토요일 수요가 강한 편이며, EDM과 힙합을 함께 다루는 대중형 운영이 강점입니다.',
                'short_description' => '주말 수요가 강한 홍대 힙합·EDM 클럽.',
                'intro_title' => '가성비로 설명하기 쉬운 홍대 주말 클럽',
                'guide_text' => '단체보다는 2~4인 소규모 방문객 안내에 적합합니다.',
                'highlight_tags' => ['주말', '가성비', '힙합', 'EDM'],
                'thumbnail' => 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=600&q=80',
                'tags' => ['힙합', 'EDM', '홍대', '금토전문'],
                'is_active' => true,
            ],
            [
                'name' => '도깨비',
                'slug' => 'dokkaebi',
                'area' => '홍대',
                'genre' => '록',
                'subgenre' => '인디',
                'vibe' => '라이브',
                'open_time' => '22:30',
                'close_time' => '06:00',
                'entry_fee_min' => 0,
                'entry_fee_max' => 20000,
                'foreigner_allowed' => true,
                'dress_code' => '자유',
                'dress_code_detail' => '드레스코드 제약이 거의 없습니다.',
                'lat' => 37.5541000,
                'lng' => 126.9216000,
                'address' => '서울 마포구 와우산로 71 지하1층',
                'instagram' => '@dokkaebi_club',
                'rating_avg' => 4.0,
                'rating_count' => 145,
                'rating_summary' => '클래식한 홍대 라이브·록 성향이 남아 있는 희소한 공간.',
                'description' => 'EDM 위주 추천이 과한 상황에서 차별화 카드로 쓰기 좋은 공간입니다. 라이브, 인디, 록 성향이 강한 고객에게 맞습니다.',
                'short_description' => '홍대 라이브·록 중심 클럽.',
                'intro_title' => '전자음악보다 밴드·록 취향에 맞는 홍대 선택지',
                'guide_text' => '대중형 클럽과 타깃이 다르므로 취향 확인 후 추천하는 편이 좋습니다.',
                'highlight_tags' => ['록', '인디', '라이브', '홍대'],
                'thumbnail' => 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=600&q=80',
                'tags' => ['록', '인디', '홍대', '라이브', '무료입장'],
                'is_active' => true,
            ],
            [
                'name' => 'vurt.',
                'slug' => 'vurt',
                'area' => '홍대',
                'genre' => '테크노',
                'subgenre' => '일렉트로닉',
                'vibe' => '언더그라운드',
                'open_time' => '23:00',
                'close_time' => '07:00',
                'entry_fee_min' => 15000,
                'entry_fee_max' => 25000,
                'foreigner_allowed' => true,
                'dress_code' => '자유',
                'dress_code_detail' => '어두운 톤과 편한 복장 위주로 안내하면 무난합니다.',
                'lat' => 37.5497000,
                'lng' => 126.9137000,
                'address' => '서울 마포구 동막로 11',
                'instagram' => '@vurt_seoul',
                'rating_avg' => 4.5,
                'rating_count' => 178,
                'rating_summary' => '국내 테크노 팬층이 두텁고 RA 이벤트 노출이 꾸준한 정통 언더그라운드 클럽.',
                'description' => '합정 인근 언더그라운드 테크노 클럽으로, 음악 중심 수요가 분명합니다. 관광형보다는 신 친화형 고객에게 추천 가치가 높습니다.',
                'short_description' => '합정권 언더그라운드 테크노 클럽.',
                'intro_title' => '사운드와 큐레이션을 중시하는 테크노 손님에게 맞는 공간',
                'guide_text' => '테이블형 소비보다 음악 감상 목적 방문 비중이 높습니다.',
                'highlight_tags' => ['테크노', '합정', '언더그라운드', '사운드'],
                'thumbnail' => 'https://images.unsplash.com/photo-1545128485-c400e7702796?w=600&q=80',
                'tags' => ['테크노', '언더그라운드', '합정', '사운드맛집'],
                'is_active' => true,
            ],
            [
                'name' => 'M2',
                'slug' => 'm2-hongdae',
                'area' => '홍대',
                'genre' => '테크노',
                'subgenre' => '하우스',
                'vibe' => '언더그라운드',
                'open_time' => '22:30',
                'close_time' => '06:00',
                'entry_fee_min' => 10000,
                'entry_fee_max' => 20000,
                'foreigner_allowed' => true,
                'dress_code' => '자유',
                'dress_code_detail' => '복장 제약이 강하지 않습니다.',
                'lat' => 37.5540000,
                'lng' => 126.9223000,
                'address' => '서울 마포구 와우산로17길 18 B2',
                'instagram' => '@m2_seoul',
                'rating_avg' => 4.2,
                'rating_count' => 156,
                'rating_summary' => '오래된 운영 이력이 있는 홍대 전자음악 클럽으로 인지도가 높습니다.',
                'description' => 'M2는 오래된 전자음악 팬층이 있는 홍대 클럽입니다. 메인스트림보다는 전자음악 기호가 있는 손님에게 설명이 잘 먹히는 편입니다.',
                'short_description' => '홍대 역사 있는 전자음악 클럽.',
                'intro_title' => '홍대 전자음악 레퍼런스로 설명하기 쉬운 이름',
                'guide_text' => '초행 손님에게는 음악 성향을 먼저 확인한 뒤 추천하는 편이 좋습니다.',
                'highlight_tags' => ['테크노', '하우스', '홍대', '전자음악'],
                'thumbnail' => 'https://images.unsplash.com/photo-1571266028243-e4733b0f0bb0?w=600&q=80',
                'tags' => ['테크노', '하우스', '홍대', '역사깊은'],
                'is_active' => true,
            ],
            [
                'name' => 'Cakeshop',
                'slug' => 'cakeshop',
                'area' => '이태원',
                'genre' => '힙합',
                'subgenre' => '일렉트로닉',
                'vibe' => '힙스터',
                'open_time' => '22:00',
                'close_time' => '05:00',
                'entry_fee_min' => 15000,
                'entry_fee_max' => 25000,
                'foreigner_allowed' => true,
                'dress_code' => '자유',
                'dress_code_detail' => '개성 있는 복장이 자연스러운 공간입니다.',
                'lat' => 37.5344000,
                'lng' => 126.9942000,
                'address' => '서울 용산구 이태원로 134 지하1층',
                'instagram' => '@cakeshopseoul',
                'rating_avg' => 4.4,
                'rating_count' => 312,
                'rating_summary' => '서울 언더그라운드 파티 씬에서 국제 인지도가 높은 대표 공간.',
                'description' => '이태원 언더그라운드 씬의 핵심 공간입니다. 해외 DJ 투어와 RA 노출 빈도가 높아 최신성 설명이 쉬운 편입니다.',
                'short_description' => '이태원 대표 언더그라운드 클럽.',
                'intro_title' => '서울 언더그라운드 신을 대표하는 이태원 레퍼런스',
                'guide_text' => '메인스트림 EDM 수요보다는 힙합·일렉트로닉·인디 신 선호 고객에게 맞습니다.',
                'highlight_tags' => ['이태원', '언더그라운드', '힙합', '일렉트로닉'],
                'thumbnail' => 'https://images.unsplash.com/photo-1598653222000-6b7b7a552625?w=600&q=80',
                'tags' => ['힙합', '일렉트로닉', '이태원', '언더그라운드'],
                'is_active' => true,
            ],
            [
                'name' => 'Faust',
                'slug' => 'faust',
                'area' => '이태원',
                'genre' => '테크노',
                'subgenre' => '일렉트로',
                'vibe' => '언더그라운드',
                'open_time' => '23:00',
                'close_time' => '07:00',
                'entry_fee_min' => 15000,
                'entry_fee_max' => 25000,
                'foreigner_allowed' => true,
                'dress_code' => '자유',
                'dress_code_detail' => '복장 규정이 빡빡하지 않고 음악 취향 비중이 큽니다.',
                'lat' => 37.5340000,
                'lng' => 126.9930000,
                'address' => '서울 용산구 보광로60길 127-15 3층',
                'instagram' => '@faustseoul',
                'rating_avg' => 4.4,
                'rating_count' => 201,
                'rating_summary' => '테크노·하우스 팬층이 꾸준하고 사운드에 대한 평가가 좋은 이태원 클럽.',
                'description' => 'Faust는 음악 성향이 분명한 이태원 클럽입니다. 메인스트림 EDM이 아닌 테크노·하우스 손님에게 우선 추천할 가치가 높습니다.',
                'short_description' => '이태원 테크노·하우스 클럽.',
                'intro_title' => '뮤직 큐레이션이 중요한 손님에게 맞는 이태원 공간',
                'guide_text' => '라인업 중심 유입이 많아 당일 DJ 정보 확인 가치가 큽니다.',
                'highlight_tags' => ['테크노', '하우스', '이태원', '사운드'],
                'thumbnail' => 'https://images.unsplash.com/photo-1545128485-c400e7702796?w=600&q=80',
                'tags' => ['테크노', '이태원', '언더그라운드', '하우스'],
                'is_active' => true,
            ],
            [
                'name' => 'Soap Seoul',
                'slug' => 'soap-seoul',
                'area' => '이태원',
                'genre' => '하우스',
                'subgenre' => '테크노',
                'vibe' => '다크',
                'open_time' => '22:00',
                'close_time' => '05:00',
                'entry_fee_min' => 20000,
                'entry_fee_max' => 30000,
                'foreigner_allowed' => true,
                'dress_code' => '자유',
                'dress_code_detail' => '어두운 톤이나 미니멀 스타일이 자연스럽습니다.',
                'lat' => 37.5349000,
                'lng' => 126.9935000,
                'address' => '서울 용산구 이태원로 217 지하2층',
                'instagram' => '@soapseoul',
                'rating_avg' => 4.3,
                'rating_count' => 168,
                'rating_summary' => '2026년 초 새 주소에서 재오픈한 이태원 하우스·테크노 중심 공간.',
                'description' => 'Soap Seoul은 이전 폐점 정보가 검색에 섞여 나오지만 2026년 기준 새 위치에서 운영 중인 것으로 확인된 공간입니다. 재오픈 정보를 기준으로 주소와 소개를 정리했습니다.',
                'short_description' => '재오픈 확인된 이태원 하우스·테크노 클럽.',
                'intro_title' => '예전 폐점 정보와 현재 운영 정보를 구분해야 하는 재오픈 케이스',
                'guide_text' => '오래된 블로그 글 대신 최근 RA 이벤트나 최근 기사 기준으로 안내하는 편이 안전합니다.',
                'highlight_tags' => ['재오픈', '하우스', '테크노', '이태원'],
                'thumbnail' => 'https://images.unsplash.com/photo-1566417713940-fe7c737a9ef2?w=600&q=80',
                'tags' => ['하우스', '테크노', '이태원', '재오픈'],
                'is_active' => true,
            ],
            [
                'name' => 'Volnost',
                'slug' => 'volnost',
                'area' => '이태원',
                'genre' => '테크노',
                'subgenre' => '일렉트로닉',
                'vibe' => '언더그라운드',
                'open_time' => '21:00',
                'close_time' => '05:00',
                'entry_fee_min' => 20000,
                'entry_fee_max' => 30000,
                'foreigner_allowed' => true,
                'dress_code' => '자유',
                'dress_code_detail' => '음악 중심 고객층이라 복장 규정은 느슨한 편입니다.',
                'lat' => 37.5342000,
                'lng' => 126.9938000,
                'address' => '서울 용산구 이태원로 136-11',
                'instagram' => '@volnostseoul',
                'rating_avg' => 4.4,
                'rating_count' => 184,
                'rating_summary' => 'RA 이벤트 운영이 활발하고 이태원 언더그라운드 라인업 신뢰도가 높은 공간.',
                'description' => 'Volnost는 최신 이벤트 확인이 비교적 쉬운 이태원 전자음악 클럽입니다. 주중보다는 금요일과 토요일 행사 강도가 높습니다.',
                'short_description' => '이태원 전자음악 이벤트 강세 클럽.',
                'intro_title' => '라인업 업데이트 추적이 쉬운 이태원 언더그라운드 공간',
                'guide_text' => '당일 이벤트 유무에 따라 매력도가 크게 달라지는 타입입니다.',
                'highlight_tags' => ['테크노', 'RA', '이태원', '언더그라운드'],
                'thumbnail' => 'https://images.unsplash.com/photo-1571266028243-e4733b0f0bb0?w=600&q=80',
                'tags' => ['테크노', '이태원', '언더그라운드', 'RA'],
                'is_active' => true,
            ],
            [
                'name' => '메이드 이태원',
                'slug' => 'made-itaewon',
                'area' => '이태원',
                'genre' => '힙합',
                'subgenre' => 'EDM',
                'vibe' => '캐주얼',
                'open_time' => '22:00',
                'close_time' => '07:00',
                'entry_fee_min' => 10000,
                'entry_fee_max' => 20000,
                'foreigner_allowed' => true,
                'dress_code' => '캐주얼',
                'dress_code_detail' => '대중형 운영이라 복장 난도가 높지 않습니다.',
                'lat' => 37.5338000,
                'lng' => 126.9925000,
                'address' => '서울 용산구 이태원로 223',
                'instagram' => '@club___made',
                'rating_avg' => 3.9,
                'rating_count' => 165,
                'rating_summary' => '이태원에서 비교적 대중형으로 접근 가능한 힙합·EDM 복합 클럽.',
                'description' => '메이드 이태원은 언더그라운드 성향보다 대중형 운영에 가깝습니다. 이태원에서 부담 없이 이동 가능한 대안으로 제시하기 좋습니다.',
                'short_description' => '이태원 대중형 힙합·EDM 클럽.',
                'intro_title' => '언더그라운드 성향이 부담스러운 손님에게 맞는 이태원 대안',
                'guide_text' => '음악 취향을 넓게 수용하는 대신 라인업 특화 강도는 낮은 편입니다.',
                'highlight_tags' => ['이태원', '대중형', '힙합', 'EDM'],
                'thumbnail' => 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=600&q=80',
                'tags' => ['힙합', 'EDM', '이태원', '대중형'],
                'is_active' => true,
            ],
            [
                'name' => '클럽레이스',
                'slug' => 'club-race',
                'area' => '강남',
                'genre' => 'EDM',
                'subgenre' => '힙합',
                'vibe' => '프리미엄',
                'open_time' => '23:00',
                'close_time' => '09:00',
                'entry_fee_min' => 20000,
                'entry_fee_max' => 30000,
                'foreigner_allowed' => true,
                'dress_code' => '스마트 캐주얼',
                'dress_code_detail' => '강남권 클럽 특성상 슬리퍼·트레이닝복은 피하는 편이 안전합니다.',
                'lat' => 37.5041000,
                'lng' => 127.0244000,
                'address' => '서울 서초구 강남대로 597 지하1층',
                'instagram' => '@clubraceseoul_official',
                'rating_avg' => 4.1,
                'rating_count' => 204,
                'rating_summary' => '강남 메인 상권에서 운영 정보 확인이 쉬운 대형 파티형 클럽.',
                'description' => '클럽레이스는 공식 사이트에 영업 요일과 시간 안내가 비교적 명확합니다. 메인스트림 EDM과 힙합 수요를 동시에 커버하는 강남형 클럽입니다.',
                'short_description' => '강남 대형 EDM·힙합 클럽.',
                'intro_title' => '영업 정보가 비교적 명확한 강남 메인스트림 클럽',
                'guide_text' => '심야보다는 자정 전후 입장 대기 관리가 중요합니다.',
                'highlight_tags' => ['강남', 'EDM', '힙합', '메인스트림'],
                'thumbnail' => 'https://images.unsplash.com/photo-1574391884720-bbc3740c59d1?w=600&q=80',
                'tags' => ['강남', 'EDM', '힙합', '대형'],
                'is_active' => true,
            ],
            [
                'name' => '옥타곤',
                'slug' => 'octagon',
                'area' => '강남',
                'genre' => 'EDM',
                'subgenre' => '하우스',
                'vibe' => '프리미엄',
                'open_time' => '23:00',
                'close_time' => '06:00',
                'entry_fee_min' => 20000,
                'entry_fee_max' => 40000,
                'foreigner_allowed' => true,
                'dress_code' => '스마트 캐주얼',
                'dress_code_detail' => '강남권 드레스코드 기준이 적용됩니다.',
                'lat' => 37.5172000,
                'lng' => 127.0286000,
                'address' => '서울 강남구 논현로 645 뉴힐탑호텔',
                'instagram' => '@octagon_seoul',
                'rating_avg' => 4.5,
                'rating_count' => 547,
                'rating_summary' => '서울에서 가장 인지도가 높은 글로벌 레벨 메인스트림 클럽 중 하나.',
                'description' => '옥타곤은 외국인 인지도와 국내 인지도가 모두 높은 강남 플래그십 클럽입니다. 처음 방문객에게도 설명이 쉬운 브랜드 파워가 있습니다.',
                'short_description' => '강남 대표 플래그십 EDM 클럽.',
                'intro_title' => '브랜드 인지도가 높은 강남 대표 클럽',
                'guide_text' => '가격대와 드레스코드 기대치가 다른 강남권 클럽보다 높은 편입니다.',
                'highlight_tags' => ['강남', '글로벌', 'EDM', '프리미엄'],
                'thumbnail' => 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=600&q=80',
                'tags' => ['글로벌', '프리미엄', 'EDM', '강남'],
                'is_active' => true,
            ],
            [
                'name' => '아르떼',
                'slug' => 'arte',
                'area' => '강남',
                'genre' => 'EDM',
                'subgenre' => '하우스',
                'vibe' => '프리미엄',
                'open_time' => '23:00',
                'close_time' => '09:00',
                'entry_fee_min' => 20000,
                'entry_fee_max' => 30000,
                'foreigner_allowed' => true,
                'dress_code' => '스마트 캐주얼',
                'dress_code_detail' => '강남권 기본 드레스코드가 적용됩니다.',
                'lat' => 37.5015000,
                'lng' => 127.0260000,
                'address' => '서울 서초구 강남대로 415 지하1층',
                'instagram' => '@arte_seoul',
                'rating_avg' => 4.0,
                'rating_count' => 141,
                'rating_summary' => '검색 결과에 오래된 폐점 언급이 섞여 있지만 현재 운영 채널이 확인되는 강남 클럽.',
                'description' => '아르떼는 오래된 폐점 후기와 현재 운영 페이지가 혼재하는 케이스입니다. 최근 운영 채널 기준으로 유지하되, 추후 재검증 우선순위를 높게 두는 것이 안전합니다.',
                'short_description' => '재검증 우선순위가 높은 강남 EDM 클럽.',
                'intro_title' => '최신 운영 채널은 있으나 주기적 재확인이 필요한 장소',
                'guide_text' => '안내 시에는 최근 운영 채널 기준이라고 보는 편이 안전합니다.',
                'highlight_tags' => ['강남', 'EDM', '재확인필요', '프리미엄'],
                'thumbnail' => 'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?w=600&q=80',
                'tags' => ['강남', 'EDM', '프리미엄', '재확인'],
                'is_active' => true,
            ],
            [
                'name' => '잭리빈',
                'slug' => 'jack-livin',
                'area' => '강남',
                'genre' => '힙합',
                'subgenre' => 'EDM',
                'vibe' => '럭셔리',
                'open_time' => '23:00',
                'close_time' => '10:00',
                'entry_fee_min' => 20000,
                'entry_fee_max' => 30000,
                'foreigner_allowed' => true,
                'dress_code' => '세미 포멀',
                'dress_code_detail' => '드레시한 스타일을 안내하는 편이 안전합니다.',
                'lat' => 37.5142000,
                'lng' => 127.0224000,
                'address' => '서울 강남구 강남대로 588 지하1층, 지하2층',
                'instagram' => '@jack_livin_seoul',
                'rating_avg' => 4.1,
                'rating_count' => 152,
                'rating_summary' => '신사역 접근성이 좋고 힙합·일렉트로닉 복합 운영을 하는 강남권 클럽.',
                'description' => '잭리빈은 강남권에서 접근성 설명이 쉬운 편입니다. 브랜드형 고급 감성과 대중형 파티 요소를 함께 갖춘 곳으로 볼 수 있습니다.',
                'short_description' => '신사역 인근 강남 힙합·EDM 클럽.',
                'intro_title' => '신사역 접근성을 강점으로 설명할 수 있는 강남권 선택지',
                'guide_text' => '압구정보다 강남·신사 동선으로 설명하는 편이 사용자 인식과 가깝습니다.',
                'highlight_tags' => ['강남', '신사', '힙합', '럭셔리'],
                'thumbnail' => 'https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?w=600&q=80',
                'tags' => ['강남', '신사', '힙합', '일렉트로닉'],
                'is_active' => true,
            ],
            [
                'name' => '사운드',
                'slug' => 'club-sound',
                'area' => '압구정',
                'genre' => 'EDM',
                'subgenre' => '힙합',
                'vibe' => '럭셔리',
                'open_time' => '23:00',
                'close_time' => '09:00',
                'entry_fee_min' => 20000,
                'entry_fee_max' => 30000,
                'foreigner_allowed' => true,
                'dress_code' => '세미 포멀',
                'dress_code_detail' => '럭셔리 클럽 성향이라 깔끔한 복장이 유리합니다.',
                'lat' => 37.5223000,
                'lng' => 127.0360000,
                'address' => '서울 강남구 도산대로 114 지하1층',
                'instagram' => '@clubsound_official',
                'rating_avg' => 4.1,
                'rating_count' => 166,
                'rating_summary' => '도산대로 입지와 공식 사이트 안내가 분명한 압구정권 메인스트림 클럽.',
                'description' => '사운드는 강남 메인스트림 수요를 안정적으로 설명하기 좋은 공간입니다. 공식 사이트에 운영 시간 안내가 비교적 명확하게 존재합니다.',
                'short_description' => '도산대로 메인스트림 EDM·힙합 클럽.',
                'intro_title' => '운영 정보 확인이 쉬운 압구정권 메인스트림 클럽',
                'guide_text' => '심야 타임 입장과 테이블 수요가 함께 발생하는 편입니다.',
                'highlight_tags' => ['압구정', '도산대로', 'EDM', '힙합'],
                'thumbnail' => 'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?w=600&q=80',
                'tags' => ['압구정', 'EDM', '힙합', '럭셔리'],
                'is_active' => true,
            ],
            [
                'name' => 'Club Nasub',
                'slug' => 'club-nasub',
                'area' => '부산 서면',
                'genre' => '테크노',
                'subgenre' => '하우스',
                'vibe' => '언더그라운드',
                'open_time' => '22:00',
                'close_time' => '04:00',
                'entry_fee_min' => 10000,
                'entry_fee_max' => 20000,
                'foreigner_allowed' => true,
                'dress_code' => '자유',
                'dress_code_detail' => '부산 언더그라운드 전자음악 성향이라 편한 복장이 무난합니다.',
                'lat' => 35.1573,
                'lng' => 129.0596,
                'address' => '부산 부산진구 중앙대로702번길 27-3',
                'instagram' => '',
                'rating_avg' => 4.3,
                'rating_count' => 87,
                'rating_summary' => '2026년 4월 Resident Advisor 이벤트가 갱신된 부산 서면 언더그라운드 클럽.',
                'description' => 'Club Nasub은 부산 서면권에서 최근 RA 이벤트 업데이트가 계속 확인되는 전자음악 중심 공간입니다. 관광형 대형클럽보다 음악 취향이 뚜렷한 손님에게 적합합니다.',
                'short_description' => '부산 서면 언더그라운드 테크노·하우스 클럽.',
                'intro_title' => '최근 이벤트 업데이트가 확인되는 부산 서면 전자음악 공간',
                'guide_text' => '최신 파티 공지가 비교적 자주 올라오는 편이라 당일 라인업 확인 가치가 높습니다.',
                'highlight_tags' => ['부산', '서면', '테크노', '언더그라운드'],
                'thumbnail' => 'https://images.unsplash.com/photo-1545128485-c400e7702796?w=600&q=80',
                'tags' => ['부산', '서면', '테크노', '하우스'],
                'is_active' => true,
            ],
            [
                'name' => 'Sanbu',
                'slug' => 'sanbu',
                'area' => '부산 서면',
                'genre' => '테크노',
                'subgenre' => '하우스',
                'vibe' => '로컬',
                'open_time' => '21:00',
                'close_time' => '04:00',
                'entry_fee_min' => 10000,
                'entry_fee_max' => 15000,
                'foreigner_allowed' => true,
                'dress_code' => '자유',
                'dress_code_detail' => '사운드바와 마이크로클럽 성격이 강해 편한 복장이 자연스럽습니다.',
                'lat' => 35.1558,
                'lng' => 129.0590,
                'address' => '부산 부산진구 중앙대로 722-9',
                'instagram' => '@sanbu_sound',
                'rating_avg' => 4.2,
                'rating_count' => 64,
                'rating_summary' => '2026년 시즌 이벤트가 이어지는 부산 서면 사운드바·마이크로클럽.',
                'description' => 'Sanbu는 부산 로컬 전자음악 씬에 가까운 공간입니다. 대형 테이블 소비형보다 음악과 분위기 중심의 방문객에게 추천하기 적합합니다.',
                'short_description' => '부산 서면 로컬 전자음악 사운드바·클럽.',
                'intro_title' => '서면권에서 로컬 전자음악 분위기를 경험하기 좋은 공간',
                'guide_text' => '메인스트림 EDM보다 하우스·테크노 계열을 찾는 사용자에게 맞습니다.',
                'highlight_tags' => ['부산', '서면', '사운드바', '테크노'],
                'thumbnail' => 'https://images.unsplash.com/photo-1566417713940-fe7c737a9ef2?w=600&q=80',
                'tags' => ['부산', '서면', '테크노', '사운드바'],
                'is_active' => true,
            ],
            [
                'name' => 'Nasub',
                'slug' => 'nasub-gwangan',
                'area' => '부산 광안리',
                'genre' => '하우스',
                'subgenre' => '디스코',
                'vibe' => '비치 라운지',
                'open_time' => '19:00',
                'close_time' => '02:00',
                'entry_fee_min' => 10000,
                'entry_fee_max' => 20000,
                'foreigner_allowed' => true,
                'dress_code' => '리조트 캐주얼',
                'dress_code_detail' => '광안리 해변가 선셋·나이트 라운지 성격이라 편한 리조트 캐주얼이 가장 무난합니다.',
                'lat' => 35.1536,
                'lng' => 129.1189,
                'address' => '부산 수영구 광안해변로 247 5층',
                'instagram' => '@nasubnasubnasub',
                'rating_avg' => 4.2,
                'rating_count' => 54,
                'rating_summary' => '2026년 4월 말 행사 페이지가 연속으로 확인되는 광안리 하우스·디스코 라운지.',
                'description' => 'Nasub은 광안리 해변권에서 하우스와 디스코 중심으로 운영되는 라운지형 공간입니다. 서면의 심야 언더그라운드와 달리 해변 동선, 이른 시작 시간, 보다 여유로운 분위기가 강점입니다.',
                'short_description' => '광안리 해변권 하우스·디스코 라운지.',
                'intro_title' => '광안리에서 선셋 이후 자연스럽게 이어가기 좋은 라운지형 나이트라이프',
                'guide_text' => '자정 이후 풀클럽보다 1차 또는 1.5차 감성의 음악 공간을 찾는 사용자에게 잘 맞습니다.',
                'highlight_tags' => ['부산', '광안리', '하우스', '디스코'],
                'thumbnail' => 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=600&q=80',
                'tags' => ['부산', '광안리', '하우스', '디스코', '라운지'],
                'is_active' => true,
            ],
            [
                'name' => 'Club Chroma',
                'slug' => 'club-chroma',
                'area' => '영종도',
                'genre' => 'EDM',
                'subgenre' => '하우스',
                'vibe' => '메가클럽',
                'open_time' => '23:00',
                'close_time' => '05:00',
                'entry_fee_min' => 70000,
                'entry_fee_max' => 150000,
                'foreigner_allowed' => true,
                'dress_code' => '스마트 캐주얼',
                'dress_code_detail' => '리조트 메가클럽 성격이라 깔끔한 복장이 유리합니다.',
                'lat' => 37.4473,
                'lng' => 126.4527,
                'address' => '인천 중구 영종해안남로321번길 186 Paradise City Chroma',
                'instagram' => '',
                'rating_avg' => 4.4,
                'rating_count' => 212,
                'rating_summary' => '공식 예매 페이지에서 2026년 운영 시간과 가격, 2026-03-03부터 2026-05-31까지 휴관 공지가 함께 확인되는 인천 메가클럽.',
                'description' => 'Club Chroma는 Paradise City 내 대형 공연형 클럽입니다. 일반 시내형 클럽보다는 쇼와 대형 이벤트를 포함한 목적지형 나이트라이프에 가깝고, 2026년 봄에는 내부 보수 공사 일정이 공식 예매 페이지에 함께 공지된 상태입니다.',
                'short_description' => '영종도 Paradise City 대형 EDM 메가클럽.',
                'intro_title' => '리조트형 목적지 나이트라이프를 대표하는 영종도 메가클럽',
                'guide_text' => '공식 Fever 공지 기준으로 2026-03-03부터 2026-05-31까지는 휴관이며, 클럽 입장 세션은 2026-06-05 이후 금·토 23:00 전후 일정 기준으로 확인됩니다.',
                'highlight_tags' => ['영종도', '리조트', 'EDM', '메가클럽'],
                'thumbnail' => 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=600&q=80',
                'tags' => ['영종도', 'EDM', '메가클럽', 'Paradise City'],
                'is_active' => CarbonImmutable::today()->gte(CarbonImmutable::parse('2026-06-05')),
            ],
            [
                'name' => 'AU Club',
                'slug' => 'au-club-daegu',
                'area' => '대구 동성로',
                'genre' => '힙합',
                'subgenre' => 'EDM',
                'vibe' => '메인스트림',
                'open_time' => '22:30',
                'close_time' => '06:00',
                'entry_fee_min' => 15000,
                'entry_fee_max' => 25000,
                'foreigner_allowed' => true,
                'dress_code' => '스마트 캐주얼',
                'dress_code_detail' => '동성로 메인스트림 클럽 성격이라 깔끔한 주말 복장이 안전합니다.',
                'lat' => 35.8690,
                'lng' => 128.5967,
                'address' => '대구 중구 동성로4길 61 1~3층',
                'phone' => '1600-6968',
                'instagram' => '@clubau_official',
                'rating_avg' => 4.0,
                'rating_count' => 91,
                'rating_summary' => '공식 사이트 위치·문의처와 2025년 DJ 5STA 활동 기사가 함께 확인되는 대구 동성로 대표 클럽.',
                'description' => 'AU Club은 대구 동성로권에서 공식 사이트로 위치와 문의처가 확인되고, 2025년 대외 DJ 활동 기사도 확인되는 메인스트림 클럽입니다. 서울 언더그라운드 스타일보다 대중형 주말 수요와 쇼 연출 중심의 운영에 가깝습니다.',
                'short_description' => '대구 동성로 메인스트림 힙합·EDM 클럽.',
                'intro_title' => '공식 사이트와 대외 활동 신호가 같이 잡히는 대구 동성로 메인스트림 선택지',
                'guide_text' => '최신 이벤트 상세는 공식 SNS 확인이 필요하지만, 운영 자체는 공식 채널 기준으로 비교적 신뢰도가 높은 편입니다.',
                'highlight_tags' => ['대구', '동성로', '힙합', '메인스트림'],
                'thumbnail' => 'https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?w=600&q=80',
                'tags' => ['대구', '동성로', '힙합', 'EDM'],
                'is_active' => true,
            ],
            [
                'name' => 'Ibija',
                'slug' => 'ibija-daejeon',
                'area' => '대전 둔산',
                'genre' => 'EDM',
                'subgenre' => '팝',
                'vibe' => '메인스트림',
                'open_time' => '22:00',
                'close_time' => '07:00',
                'entry_fee_min' => 10000,
                'entry_fee_max' => 20000,
                'foreigner_allowed' => false,
                'dress_code' => '스마트 캐주얼',
                'dress_code_detail' => '둔산 유흥가 메인스트림 클럽 기준으로 깔끔한 복장이 무난합니다.',
                'lat' => 36.3510,
                'lng' => 127.3788,
                'address' => '대전 서구 둔산동 1108',
                'instagram' => '',
                'rating_avg' => 3.6,
                'rating_count' => 42,
                'rating_summary' => 'Trip.com·Waze에서 현재 심야 운영 시간이 확인되는 대전 둔산 클럽.',
                'description' => 'Ibija는 대전 둔산권에서 운영 정보가 비교적 남아 있는 메인스트림 클럽입니다. 외국인 입장 경험 관련 후기가 좋지 않아 외국인 허용은 보수적으로 false 처리했습니다.',
                'short_description' => '대전 둔산 심야 운영 확인 클럽.',
                'intro_title' => '운영 시간은 확인되지만 입장 정책은 보수적으로 봐야 하는 대전 케이스',
                'guide_text' => '외국인 모드 추천에서는 제외하고, 로컬 메인스트림 수요 위주로 노출하는 편이 안전합니다.',
                'highlight_tags' => ['대전', '둔산', 'EDM', '재확인필요'],
                'thumbnail' => 'https://images.unsplash.com/photo-1574391884720-bbc3740c59d1?w=600&q=80',
                'tags' => ['대전', '둔산', 'EDM', '메인스트림'],
                'is_active' => true,
            ],
            [
                'name' => '올나이트',
                'slug' => 'all-night-gwangju',
                'area' => '광주 상무지구',
                'genre' => 'EDM',
                'subgenre' => '힙합',
                'vibe' => '메인스트림',
                'open_time' => '20:00',
                'close_time' => '05:00',
                'entry_fee_min' => 10000,
                'entry_fee_max' => 20000,
                'foreigner_allowed' => true,
                'dress_code' => '캐주얼',
                'dress_code_detail' => '광주 상무지구 메인 유흥 상권 기준으로 무난한 주말 복장이 적합합니다.',
                'lat' => 35.1539,
                'lng' => 126.8477,
                'address' => '광주 서구 시청로50번길 21-4 2F,3F',
                'instagram' => '',
                'rating_avg' => 3.8,
                'rating_count' => 39,
                'rating_summary' => '현재 지역 디렉터리에서 운영 시간과 상무지구 위치가 확인되는 광주 나이트클럽.',
                'description' => '올나이트는 광주 상무지구권에서 이름과 연락처 수준의 디렉터리 신호만 남아 있는 메인스트림 클럽입니다. 공식 채널이나 최신 운영 공지가 충분하지 않아 현재는 비활성 보관 상태로 두는 편이 안전합니다.',
                'short_description' => '광주 상무지구 운영 정보 확인 클럽.',
                'intro_title' => '공식 채널보다 지역 디렉터리 신호로 추적되는 광주 상무지구 선택지',
                'guide_text' => '2026-04-22 기준 공식 운영 채널이 약해 신규 노출보다는 보수적 비활성 보관이 안전합니다.',
                'highlight_tags' => ['광주', '상무지구', 'EDM', '메인스트림'],
                'thumbnail' => 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=600&q=80',
                'tags' => ['광주', '상무지구', 'EDM', '힙합'],
                'is_active' => false,
            ],
            [
                'name' => 'Club Cliff',
                'slug' => 'club-cliff-jeju',
                'area' => '제주시',
                'genre' => '힙합',
                'subgenre' => '하우스',
                'vibe' => '로컬',
                'open_time' => '21:00',
                'close_time' => '05:00',
                'entry_fee_min' => 10000,
                'entry_fee_max' => 20000,
                'foreigner_allowed' => true,
                'dress_code' => '자유',
                'dress_code_detail' => '제주 시내 로컬 클럽이라 과하게 격식을 갖출 필요는 없습니다.',
                'lat' => 33.4980,
                'lng' => 126.5315,
                'address' => '제주 제주시 광양10길 10 7층',
                'instagram' => '@clubcliffjeju',
                'rating_avg' => 4.0,
                'rating_count' => 31,
                'rating_summary' => 'Tripadvisor 기준 목요일부터 일요일까지 21:00~05:00 운영 정보가 확인되는 제주시 로컬 클럽.',
                'description' => 'Club Cliff는 제주 시내에서 힙합·하우스·테크노를 함께 표방하는 로컬 클럽입니다. 관광형 해변 라운지보다 밤 시간 집중형 클럽 성격이 강하고, 현재 공개된 운영 정보는 목요일부터 일요일 심야 영업에 초점이 맞춰져 있습니다.',
                'short_description' => '제주시 로컬 힙합·하우스 클럽.',
                'intro_title' => '관광지 바보다 늦은 시간 유입에 맞는 제주시 클럽',
                'guide_text' => 'Tripadvisor 기준 목~일 21:00~05:00 운영이라 월~수보다 주말권 일정 안내에 더 적합합니다.',
                'highlight_tags' => ['제주', '제주시', '힙합', '하우스'],
                'thumbnail' => 'https://images.unsplash.com/photo-1598653222000-6b7b7a552625?w=600&q=80',
                'tags' => ['제주', '제주시', '힙합', '하우스'],
                'is_active' => true,
            ],
            [
                'name' => 'The Cliff',
                'slug' => 'the-cliff-jeju',
                'area' => '중문',
                'genre' => '하우스',
                'subgenre' => '디스코',
                'vibe' => '비치클럽',
                'open_time' => '10:00',
                'close_time' => '02:00',
                'entry_fee_min' => 0,
                'entry_fee_max' => 20000,
                'foreigner_allowed' => true,
                'dress_code' => '리조트 캐주얼',
                'dress_code_detail' => '중문 해변 라운지 분위기라 리조트 캐주얼이 가장 잘 맞습니다.',
                'lat' => 33.2459,
                'lng' => 126.4127,
                'address' => '제주 서귀포시 중문관광로 154-17',
                'phone' => '064-738-8866',
                'instagram' => '@thecliffjeju',
                'rating_avg' => 4.3,
                'rating_count' => 233,
                'rating_summary' => 'VISITKOREA 기준 연중 운영과 일~목 10:00~24:00, 금~토 10:00~02:00가 확인되는 제주 대표 비치클럽형 라운지.',
                'description' => 'The Cliff는 엄밀한 도심 나이트클럽보다 제주 해안형 비치클럽·라운지에 가깝습니다. 일몰부터 심야까지 이어지는 분위기형 일정에 적합하며, 공식 관광 정보 기준으로 연중 운영하는 중문 대표 해변 라운지입니다.',
                'short_description' => '중문 해안 비치클럽·라운지.',
                'intro_title' => '클럽투어보다 선셋과 라운지 무드가 중요한 제주 대표 비치클럽',
                'guide_text' => '공식 관광 정보 기준으로 연중 운영하며 일~목은 24:00, 금~토는 02:00까지라 선셋부터 1차·2차 무드까지 연결하기 좋습니다.',
                'highlight_tags' => ['제주', '중문', '비치클럽', '선셋'],
                'thumbnail' => 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=600&q=80',
                'tags' => ['제주', '중문', '비치클럽', '하우스'],
                'is_active' => true,
            ],
        ];
    }

    public static function legacyClosedClubSlugs(): array
    {
        return [
            'fabric-seoul',
            'arena-club',
            'club-mass',
            'pede',
            'circle-lounge',
        ];
    }

    public static function legacyPartyPrefixes(): array
    {
        return [
            'octagon-fisher',
            'cakeshop-friday-heat',
            'fabric-techno-night',
            'arena-weekend-blast',
            'soap-dark-sessions',
            'pede-rnb-night',
            'all-night-saturday',
            'ibija-friday-main',
            'au-saturday-session',
            'nasub-friday-local',
            'sanbu-saturday-micro',
            'nasub-gwangan-friday',
            'nasub-gwangan-saturday',
            'aura-friday',
            'nb2-hiphop',
            'cakeshop-friday',
            'faust-techno-friday',
            'soap-saturday',
            'jack-livin-sat',
            'bermuda-saturday',
            'vurt-late-night',
            'volnost-underground',
            'arte-weekend',
            'made-party',
            'm2-electronic',
            'sound-luxury',
        ];
    }

    public static function generatedPartyPrefixes(): array
    {
        return collect(self::rollingPartyPrefixes())
            ->merge(self::specialPartyPrefixes())
            ->merge(self::legacyPartyPrefixes())
            ->unique()
            ->values()
            ->all();
    }

    public static function rollingPartyPrefixes(): array
    {
        return collect(self::rollingPartyTemplates())
            ->pluck('slug_prefix')
            ->values()
            ->all();
    }

    public static function specialPartyPrefixes(): array
    {
        return collect(self::specialParties())
            ->pluck('slug_prefix')
            ->values()
            ->all();
    }

    public static function partyRecords(CarbonImmutable $today, array $clubIds): array
    {
        $records = [];
        $specialPartyDateKeys = collect(self::specialParties())
            ->map(function (array $template): string {
                return $template['club_slug'].'@'.$template['event_date'];
            })
            ->flip();

        foreach (self::rollingPartyTemplates() as $template) {
            $clubId = $clubIds[$template['club_slug']] ?? null;

            if (!$clubId) {
                continue;
            }

            $date = self::nextOrSameWeekday(self::templateBaseDate($today, $template), $template['weekday']);

            if ($specialPartyDateKeys->has($template['club_slug'].'@'.$date->toDateString())) {
                continue;
            }

            $records[] = self::buildPartyRecord($template, $date, $clubId);
        }

        foreach (self::specialParties() as $template) {
            $clubId = $clubIds[$template['club_slug']] ?? null;

            if (!$clubId) {
                continue;
            }

            $date = CarbonImmutable::parse($template['event_date']);

            if ($date->lt($today)) {
                continue;
            }

            $records[] = self::buildPartyRecord($template, $date, $clubId);
        }

        return $records;
    }

    private static function rollingPartyTemplates(): array
    {
        return [
            [
                'slug_prefix' => 'race-weekend',
                'club_slug' => 'club-race',
                'name' => 'RACE WEEKEND',
                'weekday' => CarbonInterface::FRIDAY,
                'start_time' => '23:00',
                'end_time' => '09:00',
                'lineup' => 'Official operating guide',
                'ticket_price_min' => 20000,
                'ticket_price_max' => 30000,
                'genre' => 'EDM',
                'tags' => ['강남', 'EDM', '주말', '메인스트림'],
                'dress_code' => '스마트 캐주얼',
                'entry_condition' => '20세 이상 / 신분증 필수',
                'description' => 'Club Race 공식 예약 가이드와 운영 시간 안내를 기준으로 만든 대표 주말 카드입니다. 특정 DJ 확정 공지가 아니라 금요일 심야 운영 성격을 설명하기 위한 운영형 카드입니다.',
                'thumbnail' => 'https://images.unsplash.com/photo-1574391884720-bbc3740c59d1?w=600&q=80',
            ],
            [
                'slug_prefix' => 'octagon-saturday',
                'club_slug' => 'octagon',
                'name' => 'OCTAGON SATURDAY',
                'weekday' => CarbonInterface::SATURDAY,
                'start_time' => '23:00',
                'end_time' => '06:00',
                'lineup' => 'Official operating guide',
                'ticket_price_min' => 20000,
                'ticket_price_max' => 40000,
                'genre' => 'EDM',
                'tags' => ['강남', 'EDM', '토요일', '프리미엄'],
                'dress_code' => '스마트 캐주얼',
                'entry_condition' => '20세 이상 / 신분증 필수',
                'description' => 'Octagon 공식 운영 안내 기준의 토요일 대표 카드입니다. 특정 아티스트 확정 이벤트가 아니라 주말 메가클럽 운영 패턴을 보여주기 위한 운영형 카드입니다.',
                'thumbnail' => 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=600&q=80',
            ],
            [
                'slug_prefix' => 'sound-weekend-session',
                'club_slug' => 'club-sound',
                'name' => 'SOUND WEEKEND SESSION',
                'weekday' => CarbonInterface::SATURDAY,
                'start_time' => '23:00',
                'end_time' => '09:00',
                'lineup' => 'Official operating guide',
                'ticket_price_min' => 20000,
                'ticket_price_max' => 30000,
                'genre' => 'EDM',
                'tags' => ['압구정', 'EDM', '토요일', '럭셔리'],
                'dress_code' => '세미 포멀',
                'entry_condition' => '20세 이상 / 신분증 필수',
                'description' => 'Club Sound 예약 가이드에 기반한 대표 주말 카드입니다. 특정 라인업이 확정된 이벤트가 아니라 운영일과 시간대를 설명하는 목적의 카드입니다.',
                'thumbnail' => 'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?w=600&q=80',
            ],
            [
                'slug_prefix' => 'made-hongdae-friday',
                'club_slug' => 'made-hongdae',
                'name' => 'MADE HONGDAE FRIDAY',
                'weekday' => CarbonInterface::FRIDAY,
                'start_time' => '22:00',
                'end_time' => '07:30',
                'lineup' => 'Official operating guide',
                'ticket_price_min' => 10000,
                'ticket_price_max' => 15000,
                'genre' => '힙합',
                'tags' => ['홍대', '힙합', '금요일', '가성비'],
                'dress_code' => '캐주얼',
                'entry_condition' => '19세 이상 / 신분증 필수',
                'description' => '홍대 MADE 운영 요일과 입장 정보를 기준으로 만든 금요일 대표 카드입니다. 개별 아티스트가 확정된 파티가 아니라 venue 운영형 세션 안내에 가깝습니다.',
                'thumbnail' => 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=600&q=80',
            ],
            [
                'slug_prefix' => 'jack-livin-saturday',
                'club_slug' => 'jack-livin',
                'name' => 'JACK LIVIN SATURDAY',
                'weekday' => CarbonInterface::SATURDAY,
                'start_time' => '23:00',
                'end_time' => '10:00',
                'lineup' => 'Official operating guide',
                'ticket_price_min' => 20000,
                'ticket_price_max' => 30000,
                'genre' => '힙합',
                'tags' => ['강남', '힙합', '토요일', '럭셔리'],
                'dress_code' => '세미 포멀',
                'entry_condition' => '20세 이상 / 신분증 필수',
                'description' => 'Jack Livin 공식 운영 시간과 예약 안내를 반영한 토요일 대표 카드입니다. 실제 출연진이 공지된 특집 이벤트가 아니라 주말 운영 패턴을 보여주는 운영형 카드입니다.',
                'thumbnail' => 'https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?w=600&q=80',
            ],
            [
                'slug_prefix' => 'soap-weekend-session',
                'club_slug' => 'soap-seoul',
                'name' => 'SOAP WEEKEND SESSION',
                'weekday' => CarbonInterface::SATURDAY,
                'start_time' => '22:00',
                'end_time' => '05:00',
                'lineup' => 'Representative operating session',
                'ticket_price_min' => 20000,
                'ticket_price_max' => 30000,
                'genre' => '하우스',
                'tags' => ['이태원', '하우스', '토요일', '재오픈'],
                'dress_code' => '자유',
                'entry_condition' => '20세 이상 / 신분증 필수',
                'description' => 'Soap Seoul 재오픈 이후의 RA 이벤트 흐름과 운영 시간을 기준으로 만든 주말 대표 카드입니다. 특정 게스트가 확정된 공지라기보다 venue의 현재 주말 운영 성격을 보여주는 카드입니다.',
                'thumbnail' => 'https://images.unsplash.com/photo-1566417713940-fe7c737a9ef2?w=600&q=80',
            ],
            [
                'slug_prefix' => 'faust-friday',
                'club_slug' => 'faust',
                'name' => 'FAUST FRIDAY',
                'weekday' => CarbonInterface::FRIDAY,
                'start_time' => '23:00',
                'end_time' => '07:00',
                'lineup' => 'Resident-format operating guide',
                'ticket_price_min' => 15000,
                'ticket_price_max' => 25000,
                'genre' => '테크노',
                'tags' => ['이태원', '테크노', '금요일', '언더그라운드'],
                'dress_code' => '자유',
                'entry_condition' => '20세 이상 / 신분증 필수',
                'description' => 'Faust의 2026년 RA 업데이트 패턴을 기준으로 만든 금요일 대표 카드입니다. 특정 회차의 고정 라인업을 뜻하는 것은 아니며, 최근 운영 리듬을 설명하는 운영형 카드입니다.',
                'thumbnail' => 'https://images.unsplash.com/photo-1545128485-c400e7702796?w=600&q=80',
            ],
            [
                'slug_prefix' => 'chroma-saturday-main',
                'club_slug' => 'club-chroma',
                'name' => 'CHROMA SATURDAY MAIN',
                'start_date' => '2026-06-05',
                'weekday' => CarbonInterface::SATURDAY,
                'start_time' => '23:00',
                'end_time' => '05:00',
                'lineup' => 'Official admission guide',
                'ticket_price_min' => 70000,
                'ticket_price_max' => 150000,
                'genre' => 'EDM',
                'tags' => ['영종도', '리조트', '토요일', '메가클럽'],
                'dress_code' => '스마트 캐주얼',
                'entry_condition' => '19세 이상 / 신분증 필수',
                'description' => 'Club Chroma의 토요일 메인 운영 정보를 반영한 대표 카드입니다. 특정 회차의 확정 라인업이 아니라 쇼형 운영 시간과 입장 가이드를 설명하는 운영형 카드입니다.',
                'thumbnail' => 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=600&q=80',
            ],
            [
                'slug_prefix' => 'chroma-friday-club-entry',
                'club_slug' => 'club-chroma',
                'name' => 'CHROMA FRIDAY CLUB ENTRY',
                'start_date' => '2026-06-05',
                'weekday' => CarbonInterface::FRIDAY,
                'start_time' => '23:00',
                'end_time' => '04:00',
                'lineup' => 'Official admission guide',
                'ticket_price_min' => 14000,
                'ticket_price_max' => 70000,
                'genre' => 'EDM',
                'tags' => ['영종도', '리조트', '금요일', '클럽입장'],
                'dress_code' => '스마트 캐주얼',
                'entry_condition' => '19세 이상 / 신분증 필수',
                'description' => '공식 Fever 안내 기준 2026-06-05 이후 금요일 클럽 입장 세션을 반영한 대표 카드입니다. 특정 게스트 확정 이벤트가 아니라 금요일 입장 운영 정보를 보여주는 운영형 카드입니다.',
                'thumbnail' => 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=600&q=80',
            ],
            [
                'slug_prefix' => 'club-cliff-weekend',
                'club_slug' => 'club-cliff-jeju',
                'name' => 'CLUB CLIFF WEEKEND',
                'weekday' => CarbonInterface::SATURDAY,
                'start_time' => '21:00',
                'end_time' => '05:00',
                'lineup' => 'Representative operating session',
                'ticket_price_min' => 10000,
                'ticket_price_max' => 20000,
                'genre' => '힙합',
                'tags' => ['제주', '제주시', '토요일', '로컬'],
                'dress_code' => '자유',
                'entry_condition' => '19세 이상 / 신분증 필수',
                'description' => '운영 시간 정보가 확인되는 Club Cliff의 토요일 대표 카드입니다. 특정 게스트 공지가 아니라 주말 심야 운영 분위기를 설명하는 카드입니다.',
                'thumbnail' => 'https://images.unsplash.com/photo-1598653222000-6b7b7a552625?w=600&q=80',
            ],
            [
                'slug_prefix' => 'the-cliff-sunset',
                'club_slug' => 'the-cliff-jeju',
                'name' => 'THE CLIFF SUNSET SESSION',
                'weekday' => CarbonInterface::SATURDAY,
                'start_time' => '18:00',
                'end_time' => '00:00',
                'lineup' => 'Representative operating session',
                'ticket_price_min' => 0,
                'ticket_price_max' => 20000,
                'genre' => '하우스',
                'tags' => ['제주', '중문', '선셋', '비치클럽'],
                'dress_code' => '리조트 캐주얼',
                'entry_condition' => '자세한 입장 조건은 현장 공지 기준',
                'description' => 'VISITKOREA 운영 시간 정보를 기준으로 만든 The Cliff 대표 선셋 카드입니다. 고정 라인업 공지가 아니라 금·토 심야 확장 운영 성격을 보여주는 운영형 카드입니다.',
                'thumbnail' => 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=600&q=80',
            ],
        ];
    }

    private static function specialParties(): array
    {
        return [
            [
                'slug_prefix' => 'nasub-invites-dyk',
                'club_slug' => 'club-nasub',
                'name' => 'CLUB NASUB INVITES DYK',
                'event_date' => '2026-04-24',
                'start_time' => '22:00',
                'end_time' => '04:00',
                'lineup' => 'Escbr · Taz · Dyk · Kyo · Kimpro',
                'ticket_price_min' => 10000,
                'ticket_price_max' => 10000,
                'genre' => '테크노',
                'tags' => ['부산', '서면', '특집', 'RA'],
                'dress_code' => '자유',
                'entry_condition' => '19세 이상 / 신분증 필수',
                'description' => 'Resident Advisor 기준 2026-04-24 Club Nasub 특집 이벤트입니다.',
                'thumbnail' => 'https://images.unsplash.com/photo-1545128485-c400e7702796?w=600&q=80',
            ],
            [
                'slug_prefix' => 'nasub-invites-kalin',
                'club_slug' => 'club-nasub',
                'name' => 'CLUB NASUB INVITES KALIN',
                'event_date' => '2026-04-25',
                'start_time' => '22:00',
                'end_time' => '04:00',
                'lineup' => 'Subakjuice · Eunyu · Kalin · Mercy · Toka',
                'ticket_price_min' => 10000,
                'ticket_price_max' => 10000,
                'genre' => '하우스',
                'tags' => ['부산', '서면', '특집', 'RA'],
                'dress_code' => '자유',
                'entry_condition' => '19세 이상 / 신분증 필수',
                'description' => 'Resident Advisor 기준 2026-04-25 Club Nasub 특집 이벤트입니다.',
                'thumbnail' => 'https://images.unsplash.com/photo-1566417713940-fe7c737a9ef2?w=600&q=80',
            ],
            [
                'slug_prefix' => 'nasub-gwangan-invites-dyk',
                'club_slug' => 'nasub-gwangan',
                'name' => 'NASUB INVITES DYK',
                'event_date' => '2026-04-24',
                'start_time' => '19:00',
                'end_time' => '02:00',
                'lineup' => 'Dyk',
                'ticket_price_min' => 10000,
                'ticket_price_max' => 20000,
                'genre' => '하우스',
                'tags' => ['부산', '광안리', '특집', 'RA'],
                'dress_code' => '리조트 캐주얼',
                'entry_condition' => '20세 이상 / 신분증 필수',
                'description' => 'Resident Advisor 기준 2026-04-24 광안리 Nasub 특집 이벤트입니다.',
                'thumbnail' => 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=600&q=80',
            ],
            [
                'slug_prefix' => 'nasub-gwangan-invites-toka',
                'club_slug' => 'nasub-gwangan',
                'name' => 'NASUB INVITES TOKA',
                'event_date' => '2026-04-25',
                'start_time' => '19:00',
                'end_time' => '02:00',
                'lineup' => 'Toka',
                'ticket_price_min' => 10000,
                'ticket_price_max' => 20000,
                'genre' => '하우스',
                'tags' => ['부산', '광안리', '특집', 'RA'],
                'dress_code' => '리조트 캐주얼',
                'entry_condition' => '20세 이상 / 신분증 필수',
                'description' => 'Resident Advisor 기준 2026-04-25 광안리 Nasub 특집 이벤트입니다.',
                'thumbnail' => 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=600&q=80',
            ],
            [
                'slug_prefix' => 'volnost-night',
                'club_slug' => 'volnost',
                'name' => 'VOLNOST NIGHT',
                'event_date' => '2026-04-24',
                'start_time' => '23:00',
                'end_time' => '05:00',
                'lineup' => 'Recy · WEEUN KIM · NON IDENTITY',
                'ticket_price_min' => 20000,
                'ticket_price_max' => 30000,
                'genre' => '테크노',
                'tags' => ['이태원', '테크노', '특집', 'RA'],
                'dress_code' => '자유',
                'entry_condition' => '20세 이상 / 신분증 필수',
                'description' => 'Resident Advisor 기준 2026-04-24 업데이트가 확인된 Volnost 이벤트입니다.',
                'thumbnail' => 'https://images.unsplash.com/photo-1571266028243-e4733b0f0bb0?w=600&q=80',
            ],
            [
                'slug_prefix' => 'vurt-resident-night',
                'club_slug' => 'vurt',
                'name' => 'VURT RESIDENT NIGHT',
                'event_date' => '2026-04-25',
                'start_time' => '23:00',
                'end_time' => '06:00',
                'lineup' => 'Yogg · SUZAN · Djilogue',
                'ticket_price_min' => 15000,
                'ticket_price_max' => 25000,
                'genre' => '테크노',
                'tags' => ['합정', '테크노', '특집', 'RA'],
                'dress_code' => '자유',
                'entry_condition' => '20세 이상 / 신분증 필수',
                'description' => 'Resident Advisor 기준 2026-04-25 이벤트를 반영한 vurt. 상세 카드입니다.',
                'thumbnail' => 'https://images.unsplash.com/photo-1545128485-c400e7702796?w=600&q=80',
            ],
            [
                'slug_prefix' => 'cakeshop-presents-tdj',
                'club_slug' => 'cakeshop',
                'name' => 'CAKESHOP PRESENTS TDJ',
                'event_date' => '2026-05-01',
                'start_time' => '22:00',
                'end_time' => '05:00',
                'lineup' => 'TDJ · Yetsuby · Ligrye · Liu Lee · DDD · Dieman',
                'ticket_price_min' => 20000,
                'ticket_price_max' => 30000,
                'genre' => '힙합',
                'tags' => ['이태원', '특집', '게스트', 'RA'],
                'dress_code' => '자유',
                'entry_condition' => '20세 이상 / 신분증 필수',
                'description' => 'Resident Advisor 기준 2026-05-01 공연 페이지가 확인된 Cakeshop 특집 이벤트입니다.',
                'thumbnail' => 'https://images.unsplash.com/photo-1598653222000-6b7b7a552625?w=600&q=80',
            ],
        ];
    }

    private static function nextOrSameWeekday(CarbonImmutable $today, int $weekday): CarbonImmutable
    {
        return $today->dayOfWeek === $weekday
            ? $today
            : $today->next($weekday);
    }

    private static function templateBaseDate(CarbonImmutable $today, array $template): CarbonImmutable
    {
        if (!empty($template['start_date'])) {
            $startDate = CarbonImmutable::parse($template['start_date']);

            if ($startDate->gt($today)) {
                return $startDate;
            }
        }

        return $today;
    }

    private static function buildPartyRecord(array $template, CarbonImmutable $date, int $clubId): array
    {
        return [
            'club_id' => $clubId,
            'name' => $template['name'],
            'slug' => $template['slug_prefix'] . '-' . $date->format('Ymd'),
            'event_date' => $date->toDateString(),
            'start_time' => $template['start_time'],
            'end_time' => $template['end_time'],
            'lineup' => $template['lineup'],
            'ticket_price_min' => $template['ticket_price_min'],
            'ticket_price_max' => $template['ticket_price_max'],
            'genre' => $template['genre'],
            'tags' => $template['tags'],
            'dress_code' => $template['dress_code'],
            'entry_condition' => $template['entry_condition'],
            'description' => $template['description'],
            'thumbnail' => $template['thumbnail'],
            'status' => 'upcoming',
        ];
    }
}
